window.CLASES_FIN = window.CLASES_FIN || []; window.CLASES_FIN.push(
{
  "id": 103,
  "etapa": 1,
  "formato": "leccion",
  "titulo": "Tasas que engañan: tasa real, tasa efectiva, la cuota y la CAE",
  "subtitulo": "Cuánto ganas de verdad, cuánto te cuesta de verdad un crédito y cómo comparar ofertas",
  "objetivo": "Pasar de tasa nominal a real, convertir tasas mensuales y anuales, entender cómo se arma la cuota de un crédito y usar la CAE y el costo total para elegir entre créditos.",
  "gancho": "Un ejemplo oficial del SERNAC: te ofrecen **$3.000.000 en 24 cuotas de $165.799**, con una tasa de **2,08 % mensual**. Suena a 2 % al mes… pero al final pagas **$3.979.166**, casi un millón de pesos más. La **CAE** de ese crédito es **28,74 %**, no 25 % (2,08 × 12). ¿De dónde sale la diferencia? Al terminar esta lección vas a poder calcularlo, y vas a saber comparar cualquier crédito o inversión sin que te engañe la forma en que te muestran la tasa.",
  "leccion": [
    {"tipo": "predice", "pregunta": "Un depósito te paga 5 % anual. Ese año la inflación fue 4 %. ¿Cuánto aumentó de verdad tu poder de compra?", "opciones": ["5 %", "Cerca de 1 %", "9 %", "Nada: perdiste"], "respuestas": ["Cerca de 1 %"], "explicacion": "Tu plata creció 5 %, pero los precios subieron 4 %. En poder de compra ganaste (1,05 / 1,04) − 1 = **0,96 %**. Esa es la **tasa real**."},
    {"tipo": "texto", "titulo": "Tasa nominal vs. tasa real", "texto": "- **Tasa nominal**: la que te dicen, en pesos. Cuánto crece tu **dinero**.\n- **Tasa real**: descontada la inflación. Cuánto crece tu **poder de compra**.\n\nSe relacionan con la **ecuación de Fisher**:\n**(1 + nominal) = (1 + real) × (1 + inflación)**\n\nAtajo: real ≈ nominal − inflación (funciona bien con tasas bajas).\n\nEn Chile, los instrumentos **en UF** (depósitos, créditos hipotecarios) se expresan directamente en tasa real: 'UF + 2 %' significa 2 % real.", "porque": "Si la tasa real es **negativa**, pierdes poder de compra aunque 'ganes' intereses. Y una deuda con tasa real baja es más barata de lo que parece cuando hay inflación."},
    {"tipo": "ejemplo", "titulo": "De nominal a real", "planteamiento": "Un depósito paga 8 % nominal anual y la inflación es 3 %. ¿Tasa real?", "pasos": [
      {"texto": "Despeja la real de Fisher.", "calculo": "real = (1 + nominal) / (1 + inflación) − 1"},
      {"texto": "Reemplaza.", "calculo": "1,08 / 1,03 − 1 = 1,04854 − 1 = 4,85 %"},
      {"texto": "El atajo da 8 − 3 = 5 %: cerca, pero un poco más alto que el exacto."}
    ], "resultado": "Tasa real = 4,85 %."},
    {"tipo": "turno", "pregunta": "Una inversión rinde {n} % nominal anual y la inflación es {pi} %. ¿Tasa real exacta? (%, 2 decimales; negativa si pierdes)", "params": {"n": [2, 14, 0.5], "pi": [1, 12, 0.5]}, "formula": "((1+n/100)/(1+pi/100)-1)*100", "tolerancia": 0.02, "unidad": "%", "pista": "real = (1 + n/100) / (1 + pi/100) − 1.", "explicacion": "(1 + {n}/100) / (1 + {pi}/100) − 1 = {=((1+n/100)/(1+pi/100)-1)*100} %."},
    {"tipo": "pregunta", "pregunta": "Tu cuenta paga 2 % anual y la inflación es 4 %. ¿Qué pasa?", "opciones": ["Tienes más pesos, pero pierdes poder de compra (tasa real negativa)", "Ganas 2 % real", "No cambia nada", "Ganas 6 %"], "respuestas": ["Tienes más pesos, pero pierdes poder de compra (tasa real negativa)"], "explicacion": "1,02 / 1,04 − 1 = **−1,92 %**. Tu saldo sube, pero compra menos."},
    {"tipo": "texto", "titulo": "Mensual no es anual ÷ 12", "texto": "Los créditos en Chile se informan con **tasa mensual**. Para compararla con una anual hay que **componerla**:\n\n- **Anual efectiva** = (1 + mensual)¹² − 1\n- **Mensual equivalente** = (1 + anual)^(1/12) − 1\n\nMultiplicar la mensual por 12 da una **tasa anual nominal**, que es **menor** que la efectiva, porque ignora el interés sobre interés.", "porque": "Al comparar un crédito informado 'al mes' con una inversión informada 'al año', hay que llevar las dos a la misma base. Si no, comparas peras con manzanas."},
    {"tipo": "ejemplo", "titulo": "2 % mensual, ¿cuánto es al año?", "planteamiento": "Una deuda cobra 2 % mensual. ¿Cuál es su tasa anual efectiva?", "pasos": [
      {"texto": "Compón 12 meses.", "calculo": "(1,02)¹² = 1,26824"},
      {"texto": "Resta 1.", "calculo": "1,26824 − 1 = 26,82 %"},
      {"texto": "Si multiplicaras 2 % × 12 obtendrías 24 %: subestimas el costo en casi 3 puntos."}
    ], "resultado": "2 % mensual = 26,82 % anual efectiva."},
    {"tipo": "turno", "pregunta": "Una tarjeta cobra {m} % mensual. ¿Cuál es su tasa anual efectiva? (%, 2 decimales)", "params": {"m": [0.5, 3.5, 0.1]}, "formula": "(Math.pow(1+m/100,12)-1)*100", "tolerancia": 0.02, "unidad": "%", "pista": "(1 + m/100)¹² − 1.", "explicacion": "(1 + {m}/100)¹² − 1 = {=(Math.pow(1+m/100,12)-1)*100} % (× 12 daría {=m*12} %)."},
    {"tipo": "turno", "pregunta": "Una inversión rinde {a} % anual efectivo. ¿Cuál es la tasa mensual equivalente? (%, 3 decimales)", "params": {"a": [3, 15, 0.5]}, "formula": "(Math.pow(1+a/100,1/12)-1)*100", "tolerancia": 0.002, "unidad": "%", "pista": "(1 + a/100)^(1/12) − 1.", "explicacion": "(1 + {a}/100)^(1/12) − 1 = {=(Math.pow(1+a/100,1/12)-1)*100} % mensual (no {=a/12} %)."},
    {"tipo": "texto", "titulo": "Cómo se arma la cuota de un crédito", "texto": "Casi todos los créditos de consumo e hipotecarios usan **cuota fija** (sistema francés):\n\n**Cuota = Monto × i / [1 − (1 + i)^(−n)]**\n\n(i = tasa del período, n = número de cuotas)\n\nCada mes, de la cuota:\n- primero se pagan los **intereses** del saldo que debes (saldo × i);\n- el resto **amortiza** (baja) la deuda.\n\nAl principio la deuda es grande, así que casi toda la cuota es interés; al final, casi toda es capital.", "diagrama": "amortizacion", "porque": "Por eso, si prepagas un crédito al comienzo te ahorras muchos intereses, y si lo prepagas al final, casi nada. Y por eso alargar el plazo baja la cuota pero sube mucho el total."},
    {"tipo": "ejemplo", "titulo": "$2.000.000 al 1,5 % mensual en 24 cuotas", "planteamiento": "Calcula la cuota, cómo se reparte la primera y cuánto pagas en total.", "pasos": [
      {"texto": "Cuota con la fórmula.", "calculo": "1,015⁻²⁴ = 0,69954\nCuota = 2.000.000 × 0,015 / (1 − 0,69954) = 30.000 / 0,30046 = $99.848"},
      {"texto": "Primera cuota: interés sobre el saldo inicial; el resto amortiza.", "calculo": "Interés = 2.000.000 × 0,015 = $30.000\nAmortización = 99.848 − 30.000 = $69.848\nNuevo saldo = 2.000.000 − 69.848 = $1.930.152"},
      {"texto": "Total pagado e intereses.", "calculo": "24 × 99.848 = $2.396.352\nIntereses = 2.396.352 − 2.000.000 = $396.352"}
    ], "resultado": "Cuota $99.848; pagas $396.352 de intereses (20 % del monto)."},
    {"tipo": "turno", "pregunta": "Un crédito de ${P} al {i} % mensual en {n} cuotas fijas. ¿Valor de la cuota? (redondea)", "params": {"P": [500000, 5000000, 100000], "i": [0.8, 3, 0.1], "n": [6, 48, 6]}, "formula": "P*(i/100)/(1-Math.pow(1+i/100,-n))", "tolRel": 0.001, "unidad": "$", "pista": "Cuota = P × i / [1 − (1 + i)^(−n)], con i en decimal.", "explicacion": "{P} × {=i/100} / [1 − (1 + {=i/100})^(−{n})] = ${=Math.round(P*(i/100)/(1-Math.pow(1+i/100,-n)))}. Total: ${=Math.round(n*P*(i/100)/(1-Math.pow(1+i/100,-n)))}."},
    {"tipo": "pregunta", "pregunta": "El mismo crédito de $2.000.000 al 1,5 % mensual, pero en **48** cuotas en vez de 24. ¿Qué pasa?", "opciones": ["La cuota baja a ~$58.750, pero pagas ~$820.000 de intereses (más del doble)", "La cuota baja a la mitad y los intereses no cambian", "La cuota sube", "Pagas menos intereses porque la cuota es menor"], "respuestas": ["La cuota baja a ~$58.750, pero pagas ~$820.000 de intereses (más del doble)"], "explicacion": "Cuota a 48 meses = $58.750; total 48 × 58.750 = $2.820.000 → **$820.000** de intereses, contra $396.352 a 24 meses. Una cuota más baja no significa un crédito más barato."},
    {"tipo": "texto", "titulo": "La CAE: el costo real de un crédito en un solo número", "texto": "Además de los intereses, un crédito de consumo trae **seguros** (desgravamen, cesantía), **gastos notariales** e **impuesto de timbres y estampillas**. Por eso en Chile, desde la **Ley 20.555 (2011, 'SERNAC Financiero')**, se debe informar la **CAE (Carga Anual Equivalente)**:\n\n- Se busca la **tasa mensual** que hace que el **valor presente de todas las cuotas** sea igual al **monto líquido** que recibes.\n- Esa tasa se **multiplica por 12**.\n\nTambién se debe informar el **costo total del crédito**: la suma de todo lo que pagarás.\n\nPara comparar créditos de **igual monto y plazo**, mira la **CAE** y el **costo total**, no la tasa ni la cuota.", "porque": "Dos créditos con la misma tasa pueden tener costos muy distintos por los seguros y gastos. La CAE los incluye todos."},
    {"tipo": "ejemplo", "titulo": "El ejemplo oficial del SERNAC", "planteamiento": "Recibes $3.000.000 líquidos en 24 cuotas al 2,08 % mensual. Seguro de desgravamen $24.356, seguro de cesantía $57.537, gastos notariales $1.111 e impuesto $24.664.", "pasos": [
      {"texto": "Los seguros, gastos e impuesto se **suman a la deuda**: el **monto bruto** es mayor que lo que recibes.", "calculo": "3.000.000 + 24.356 + 57.537 + 1.111 + 24.664 = $3.107.668"},
      {"texto": "La cuota se calcula al 2,08 % sobre el monto bruto.", "calculo": "Cuota = 3.107.668 × 0,0208 / [1 − 1,0208⁻²⁴] = $165.799"},
      {"texto": "Pero tú recibiste $3.000.000. ¿Qué tasa mensual iguala $3.000.000 con 24 cuotas de $165.799? Se busca por tanteo (la calculadora lo hace): **2,39 %**.", "calculo": "3.000.000 = Σ 165.799 / (1 + i)ᵏ, k = 1…24  →  i = 2,395 %"},
      {"texto": "CAE y costo total.", "calculo": "CAE = 2,395 % × 12 = 28,74 %\nCosto total = 24 × 165.798,6 = $3.979.166\n(con la cuota redondeada a $165.799 daría $3.979.176)"}
    ], "resultado": "La tasa 'de vitrina' es 2,08 % mensual; el costo real es 2,39 % mensual (CAE 28,74 %). La diferencia la ponen los seguros, gastos e impuesto."},
    {"tipo": "calc", "titulo": "Experimenta: reproduce el ejemplo del SERNAC", "tarea": "Pon monto **3.107.668**, tasa **2,08**, **24** cuotas, gastos iniciales descontados **107.668** y seguros mensuales **0**. Comprueba la cuota ($165.799) y la CAE (~28,7 %). Después pon gastos **0**: ¿cuánto baja la CAE?", "calc": "credito"},
    {"tipo": "pregunta", "pregunta": "Dos créditos de **igual monto y plazo**: A tiene tasa 1,9 % mensual y CAE 31 %; B tiene tasa 2,1 % mensual y CAE 27 %. ¿Cuál es más barato?", "opciones": ["B, porque su CAE es menor", "A, porque su tasa es menor", "Son iguales", "No se puede saber sin la cuota"], "respuestas": ["B, porque su CAE es menor"], "explicacion": "A tiene una tasa menor, pero seguros o gastos más caros. La CAE incluye todo: con igual monto y plazo, **la menor CAE (y el menor costo total) es el crédito más barato**."},
    {"tipo": "pregunta", "pregunta": "La CAE del ejemplo es 28,74 % (2,395 % × 12). Si compones esa tasa mensual 12 meses, la tasa anual efectiva es…", "opciones": ["mayor que 28,74 % (cerca de 32,8 %)", "exactamente 28,74 %", "menor que 28,74 %", "25 %"], "respuestas": ["mayor que 28,74 % (cerca de 32,8 %)"], "explicacion": "1,02395¹² − 1 = **32,8 %**. La CAE se anualiza multiplicando por 12 (así lo define el reglamento), así que es menor que la tasa efectiva. Sirve para comparar créditos entre sí, no para compararlos con una inversión informada en tasa efectiva."},
    {"tipo": "texto", "titulo": "El tope legal: la tasa máxima convencional", "texto": "La **Ley 18.010** fija un tope. Su **artículo 6°** prohíbe pactar un interés que exceda **en más de 50 %** al **interés corriente** (el promedio del mercado que calcula la **CMF**). Es decir:\n\n**Tasa máxima convencional = interés corriente × 1,5**\n\nLa CMF publica las tasas cada mes, en la primera quincena, por tipo de operación (monto, plazo, moneda). Según el **artículo 8°**, si se pacta un interés mayor, ese pacto se tiene por no escrito y el interés se **reduce al interés corriente**. Las tarjetas de crédito tienen reglas propias (art. 6° ter).", "porque": "Que un crédito esté bajo el tope **no** significa que sea barato: 'a la tasa máxima' es de lo más caro que permite la ley."},
    {"tipo": "turno", "pregunta": "Para cierto tipo de crédito, la CMF publica un interés corriente de {ic} % anual. ¿Cuál es la tasa máxima convencional? (%, 2 decimales)", "params": {"ic": [8, 32, 0.25]}, "formula": "ic*1.5", "tolerancia": 0.01, "unidad": "%", "pista": "TMC = interés corriente × 1,5.", "explicacion": "{ic} × 1,5 = {=ic*1.5} % anual."},
    {"tipo": "reflexion", "consigna": "Un amigo te dice: 'Saqué un crédito al 2,08 % mensual, o sea como 25 % al año'. Explícale por qué en realidad le cuesta más y cómo debería comparar créditos.", "modelo": "La tasa de 2,08 % es solo el interés sobre la deuda. Pero la deuda incluye seguros, gastos notariales e impuestos que se sumaron al monto: recibiste $3.000.000 pero debes $3.107.668. La tasa que iguala lo que recibiste con lo que pagas es 2,39 % mensual, y por eso la CAE es 28,74 %. Además, 2,08 × 12 = 25 % no es la tasa anual efectiva: componiendo es más. Para comparar créditos del mismo monto y plazo hay que mirar la CAE y el costo total, no la tasa ni la cuota.", "claves": ["Los seguros, gastos e impuesto se suman a la deuda", "La CAE es la tasa que iguala lo recibido con las cuotas, × 12", "Mensual × 12 subestima la tasa efectiva", "Comparar por CAE y costo total, con igual monto y plazo"]},
    {"tipo": "resumen", "puntos": ["**Fisher**: (1 + nominal) = (1 + real)(1 + inflación); real ≈ nominal − inflación.", "**Anual efectiva** = (1 + mensual)¹² − 1; mensual × 12 la subestima.", "**Cuota fija** = P × i / [1 − (1 + i)⁻ⁿ]; al comienzo se paga sobre todo interés.", "Alargar el plazo baja la cuota pero **sube el costo total**.", "**CAE** (Ley 20.555): tasa mensual que iguala lo recibido con lo pagado × 12; incluye seguros y gastos. Compara por **CAE y costo total**.", "**Tasa máxima convencional** = interés corriente × 1,5 (Ley 18.010, art. 6°); bajo el tope no significa barato."]}
  ],
  "caso": {
    "titulo": "Caso práctico: financiar una máquina para tu negocio de jugos",
    "contexto": "Necesitas una **extractora industrial de $2.500.000** (precio contado, ejemplo ilustrativo). Tienes dos ofertas a **24 meses**:\n- **A · Banco**: crédito de consumo al **1,6 % mensual**. Seguros y gastos por **$90.000** se suman a la deuda (monto bruto $2.590.000).\n- **B · Casa comercial**: '**24 cuotas de $135.000**', sin mencionar tasa.\nCon la máquina estimas vender **200 botellas más al mes**, con un margen de **$630** cada una (el margen que calculaste en el caso de la clase 1).",
    "pasos": [
      {"tipo": "predice", "pregunta": "A primera vista, ¿cuál crees que es más barata?", "opciones": ["A · Banco", "B · Casa comercial", "Iguales", "No se puede saber"], "respuestas": ["A · Banco"], "explicacion": "Hay que calcularlo, pero sí: la clave es comparar el **costo total** y la **CAE** de ambas, no la cuota ni la tasa. Vamos paso a paso."},
      {"tipo": "pregunta", "pregunta": "Oferta A: ¿cuál es la cuota? (monto bruto $2.590.000, 1,6 % mensual, 24 cuotas; redondea)", "respuesta": 130810, "tolerancia": 2, "como": "numero", "unidad": "$", "pista": "Cuota = 2.590.000 × 0,016 / [1 − 1,016⁻²⁴].", "explicacion": "2.590.000 × 0,016 / (1 − 1,016⁻²⁴) = **$130.810**. Costo total: 24 × 130.810,13 = $3.139.443."},
      {"tipo": "pregunta", "pregunta": "Oferta B: ¿cuál es el costo total (todo lo que pagas)?", "respuesta": 3240000, "tolerancia": 1, "como": "numero", "unidad": "$", "explicacion": "24 × 135.000 = **$3.240.000**, $740.000 más que el precio contado."},
      {"tipo": "pregunta", "pregunta": "Con la calculadora (o por tanteo): la tasa mensual que iguala $2.500.000 con 24 cuotas de $135.000 es 2,19 %. ¿Cuál es la CAE de B? (%, 1 decimal)", "respuesta": 26.2, "tolerancia": 0.15, "como": "numero", "unidad": "%", "pista": "CAE = tasa mensual × 12.", "explicacion": "2,187 % × 12 = **26,2 %**. La de A, con lo que recibes ($2.500.000) y sus cuotas, es **22,9 %**: aunque A cobra 1,6 % 'de vitrina', su costo real es 1,91 % mensual por los $90.000 de seguros y gastos."},
      {"tipo": "pregunta", "pregunta": "Entonces, ¿qué oferta es más barata y por cuánto (en costo total)?", "opciones": ["A, por unos $100.557", "B, por unos $100.557", "A, por unos $4.190 al mes y nada más", "Son iguales"], "respuestas": ["A, por unos $100.557"], "explicacion": "Costo total A $3.139.443 vs. B $3.240.000: **A es más barata por $100.557**, y su CAE es menor (22,9 % vs. 26,2 %)."},
      {"tipo": "pregunta", "pregunta": "¿La máquina 'se paga sola'? Compara el margen extra mensual (200 × $630) con la cuota de A.", "opciones": ["Casi: el margen extra ($126.000) cubre el 96 % de la cuota ($130.810)", "Sí, sobra mucho dinero", "No, cubre menos de la mitad", "No se puede saber"], "respuestas": ["Casi: el margen extra ($126.000) cubre el 96 % de la cuota ($130.810)"], "explicacion": "200 × 630 = $126.000 al mes. Te faltan $4.810 al mes durante 2 años, y después la máquina es tuya y sigue generando $126.000 al mes. Si vendes 208 botellas extra o más (130.810 / 630), se paga sola desde el primer mes."},
      {"tipo": "reflexion", "consigna": "Escribe tu decisión: ¿comprarías la máquina? ¿Con qué oferta? Justifica con la CAE, el costo total y el margen que genera.", "modelo": "Compraría la máquina con el crédito del banco (A). Aunque su tasa de vitrina es 1,6 %, con los seguros y gastos la CAE es 22,9 %, más baja que la de la casa comercial (26,2 %), y el costo total es $100.557 menor ($3.139.443 vs. $3.240.000). La cuota de $130.810 queda casi cubierta por el margen extra de 200 botellas al mes ($126.000); con 8 botellas más al mes ya se paga sola. Antes de firmar, pediría la hoja resumen con la CAE oficial y preguntaría si los seguros son obligatorios.", "claves": ["Comparar por CAE y costo total, no por la cuota", "A: CAE 22,9 %, total $3.139.443", "B: CAE 26,2 %, total $3.240.000", "Margen extra $126.000 vs. cuota $130.810", "Pedir la CAE oficial y revisar los seguros"]}
    ]
  },
  "desafio": [
    {"tipo": "numero", "pregunta": "Nominal {n} % anual, inflación {pi} %. ¿Tasa real exacta? (%, 2 decimales)", "params": {"n": [2, 14, 0.5], "pi": [1, 12, 0.5]}, "formula": "((1+n/100)/(1+pi/100)-1)*100", "tolerancia": 0.02, "unidad": "%", "explicacion": "(1 + {n}/100)/(1 + {pi}/100) − 1 = {=((1+n/100)/(1+pi/100)-1)*100} %."},
    {"tipo": "numero", "pregunta": "Quieres una tasa real de {r} % y esperas inflación de {pi} %. ¿Qué tasa nominal necesitas? (%, 2 decimales)", "params": {"r": [1, 6, 0.5], "pi": [2, 8, 0.5]}, "formula": "((1+r/100)*(1+pi/100)-1)*100", "tolerancia": 0.02, "unidad": "%", "explicacion": "(1 + {r}/100)(1 + {pi}/100) − 1 = {=((1+r/100)*(1+pi/100)-1)*100} %."},
    {"tipo": "numero", "pregunta": "{m} % mensual. ¿Tasa anual efectiva? (%, 2 decimales)", "params": {"m": [0.5, 3.5, 0.1]}, "formula": "(Math.pow(1+m/100,12)-1)*100", "tolerancia": 0.02, "unidad": "%", "explicacion": "(1 + {m}/100)¹² − 1 = {=(Math.pow(1+m/100,12)-1)*100} %."},
    {"tipo": "numero", "pregunta": "{a} % anual efectivo. ¿Tasa mensual equivalente? (%, 3 decimales)", "params": {"a": [3, 30, 0.5]}, "formula": "(Math.pow(1+a/100,1/12)-1)*100", "tolerancia": 0.002, "unidad": "%", "explicacion": "(1 + {a}/100)^(1/12) − 1 = {=(Math.pow(1+a/100,1/12)-1)*100} %."},
    {"tipo": "numero", "pregunta": "Crédito de ${P} al {i} % mensual en {n} cuotas fijas. ¿Cuota? (redondea)", "params": {"P": [500000, 5000000, 100000], "i": [0.8, 3, 0.1], "n": [6, 48, 6]}, "formula": "P*(i/100)/(1-Math.pow(1+i/100,-n))", "tolRel": 0.001, "unidad": "$", "explicacion": "Cuota = ${=Math.round(P*(i/100)/(1-Math.pow(1+i/100,-n)))}."},
    {"tipo": "numero", "pregunta": "Crédito de ${P} al {i} % mensual en {n} cuotas fijas. ¿Cuánto pagas de intereses en total? (redondea)", "params": {"P": [500000, 5000000, 100000], "i": [0.8, 3, 0.1], "n": [6, 48, 6]}, "formula": "n*P*(i/100)/(1-Math.pow(1+i/100,-n))-P", "tolRel": 0.003, "unidad": "$", "explicacion": "{n} × cuota − {P} = ${=Math.round(n*P*(i/100)/(1-Math.pow(1+i/100,-n))-P)}."},
    {"tipo": "numero", "pregunta": "Crédito de ${P} al {i} % mensual. En la PRIMERA cuota, ¿cuánto es interés? (redondea)", "params": {"P": [500000, 5000000, 100000], "i": [0.8, 3, 0.1]}, "formula": "P*i/100", "tolerancia": 1, "unidad": "$", "explicacion": "Interés = saldo × tasa = {P} × {i}/100 = ${=Math.round(P*i/100)}."},
    {"tipo": "numero", "pregunta": "Interés corriente publicado por la CMF: {ic} % anual. ¿Tasa máxima convencional? (%, 2 decimales)", "params": {"ic": [8, 32, 0.25]}, "formula": "ic*1.5", "tolerancia": 0.01, "unidad": "%", "explicacion": "{ic} × 1,5 = {=ic*1.5} %."},
    {"tipo": "numero", "pregunta": "La tasa mensual que iguala lo que recibes con las cuotas de un crédito es {t} %. ¿Cuál es su CAE? (%, 2 decimales)", "params": {"t": [1, 4, 0.05]}, "formula": "t*12", "tolerancia": 0.01, "unidad": "%", "explicacion": "CAE = {t} × 12 = {=t*12} %."},
    {"tipo": "alternativas", "pregunta": "Para comparar dos créditos de igual monto y plazo, ¿qué miras?", "opciones": ["La CAE y el costo total", "La tasa de interés mensual", "La cuota más baja", "El banco más conocido"], "respuestas": ["La CAE y el costo total"], "explicacion": "Incluyen seguros, gastos e impuestos."},
    {"tipo": "alternativas", "pregunta": "¿Qué pasa con una cuota fija a lo largo del crédito?", "opciones": ["Al inicio es casi todo interés y al final casi todo capital", "Siempre es mitad interés y mitad capital", "Al inicio es casi todo capital", "Es solo interés hasta la última cuota"], "respuestas": ["Al inicio es casi todo interés y al final casi todo capital"], "explicacion": "El interés se calcula sobre el saldo, que va bajando."},
    {"tipo": "alternativas", "pregunta": "Alargas un crédito de 24 a 48 cuotas (misma tasa). ¿Qué ocurre?", "opciones": ["Baja la cuota y sube el total de intereses", "Baja la cuota y bajan los intereses", "Sube la cuota", "No cambia nada"], "respuestas": ["Baja la cuota y sube el total de intereses"], "explicacion": "Debes más tiempo, así que pagas intereses más meses."},
    {"tipo": "alternativas", "pregunta": "Un crédito se pactó por sobre la tasa máxima convencional. Según la Ley 18.010 (art. 8°)…", "opciones": ["El interés se reduce al interés corriente", "El crédito queda gratis", "Se mantiene lo pactado", "Se duplica la tasa"], "respuestas": ["El interés se reduce al interés corriente"], "explicacion": "El pacto que excede el máximo se tiene por no escrito."},
    {"tipo": "escritura", "pregunta": "En 60+ palabras: explica por qué la tasa de interés de un crédito no muestra su costo real y qué es la CAE.", "minPalabras": 60, "obligatorias": ["CAE", "seguros", "costo total", "tasa"]}
  ],
  "repaso": [
    {"tipo": "numero", "etiqueta": "Tasa real", "pregunta": "Nominal {n} %, inflación {pi} %. ¿Real exacta? (%, 2 decimales)", "params": {"n": [2, 12, 0.5], "pi": [1, 10, 0.5]}, "formula": "((1+n/100)/(1+pi/100)-1)*100", "tolerancia": 0.02, "unidad": "%", "explicacion": "{=((1+n/100)/(1+pi/100)-1)*100} %."},
    {"tipo": "numero", "etiqueta": "Mensual → anual", "pregunta": "{m} % mensual = ¿% anual efectivo? (2 decimales)", "params": {"m": [0.5, 3, 0.1]}, "formula": "(Math.pow(1+m/100,12)-1)*100", "tolerancia": 0.02, "unidad": "%", "explicacion": "(1 + {m}/100)¹² − 1 = {=(Math.pow(1+m/100,12)-1)*100} %."},
    {"tipo": "numero", "etiqueta": "Cuota fija", "pregunta": "${P} al {i} % mensual en {n} cuotas. ¿Cuota? (redondea)", "params": {"P": [500000, 3000000, 100000], "i": [1, 2.5, 0.1], "n": [12, 36, 6]}, "formula": "P*(i/100)/(1-Math.pow(1+i/100,-n))", "tolRel": 0.001, "unidad": "$", "explicacion": "${=Math.round(P*(i/100)/(1-Math.pow(1+i/100,-n)))}."},
    {"tipo": "alternativas", "etiqueta": "Comparar créditos", "pregunta": "A: tasa 1,8 %, CAE 30 %. B: tasa 2,0 %, CAE 26 %. Mismo monto y plazo. Más barato:", "opciones": ["B", "A", "Iguales", "Depende de la cuota"], "respuestas": ["B"], "explicacion": "Menor CAE = menor costo, con igual monto y plazo."},
    {"tipo": "alternativas", "etiqueta": "Qué incluye la CAE", "pregunta": "La CAE incluye…", "opciones": ["intereses, seguros, gastos e impuestos", "solo la tasa de interés", "solo los seguros", "la inflación"], "respuestas": ["intereses, seguros, gastos e impuestos"], "explicacion": "Todos los costos del crédito, en un porcentaje anual."},
    {"tipo": "alternativas", "etiqueta": "Cómo se calcula la CAE", "pregunta": "La CAE se calcula como…", "opciones": ["tasa mensual que iguala lo recibido con las cuotas × 12", "tasa mensual ^ 12", "tasa de interés + 5 %", "costo total / monto"], "respuestas": ["tasa mensual que iguala lo recibido con las cuotas × 12"], "explicacion": "Así lo define el reglamento (ejemplo SERNAC: 2,39 % × 12 = 28,74 %)."},
    {"tipo": "numero", "etiqueta": "Tasa máxima", "pregunta": "Interés corriente {ic} %. ¿Tasa máxima convencional? (%, 2 decimales)", "params": {"ic": [8, 30, 0.5]}, "formula": "ic*1.5", "tolerancia": 0.01, "unidad": "%", "explicacion": "{ic} × 1,5 = {=ic*1.5} %."},
    {"tipo": "alternativas", "etiqueta": "Tasa real negativa", "pregunta": "Tu cuenta paga 1 % y la inflación es 5 %. Tu tasa real es…", "opciones": ["negativa: pierdes poder de compra", "positiva", "cero", "6 %"], "respuestas": ["negativa: pierdes poder de compra"], "explicacion": "1,01 / 1,05 − 1 = −3,8 %."},
    {"tipo": "alternativas", "etiqueta": "Plazo y costo", "pregunta": "Una cuota más baja por alargar el plazo significa…", "opciones": ["más intereses en total", "un crédito más barato", "menos seguros", "una CAE menor siempre"], "respuestas": ["más intereses en total"], "explicacion": "Ejemplo: $2 M al 1,5 %: 24 cuotas → $396.352 de intereses; 48 cuotas → $820.000."},
    {"tipo": "alternativas", "etiqueta": "UF + tasa", "pregunta": "Un depósito en 'UF + 2 %' te da…", "opciones": ["2 % real (sobre la inflación)", "2 % nominal", "2 % menos la inflación", "la inflación menos 2 %"], "respuestas": ["2 % real (sobre la inflación)"], "explicacion": "La UF ya ajusta por inflación; la tasa que se suma es real."}
  ],
  "ficha": {
    "ideas": ["**Nominal** = crecimiento del dinero; **real** = crecimiento del poder de compra.", "Créditos en Chile: tasa **mensual**; para comparar con anual, **componer**.", "**Cuota fija**: el interés se calcula sobre el saldo; al inicio pagas sobre todo interés.", "**Plazo más largo** = cuota menor pero más intereses totales.", "**CAE** (Ley 20.555): incluye seguros, gastos e impuestos; compara con **CAE y costo total**, a igual monto y plazo.", "**Tasa máxima convencional** = interés corriente × 1,5 (Ley 18.010); la CMF publica las tasas cada mes."],
    "formulas": ["Fisher: (1 + n) = (1 + r)(1 + π)  →  r = (1 + n)/(1 + π) − 1", "Aprox.: r ≈ n − π", "Anual efectiva = (1 + i_m)¹² − 1", "Mensual equivalente = (1 + i_a)^(1/12) − 1", "Cuota = P × i / [1 − (1 + i)⁻ⁿ]", "Interés del mes = saldo × i ; amortización = cuota − interés", "CAE = i (que iguala lo recibido con las cuotas) × 12", "Costo total = suma de todas las cuotas y pagos", "TMC = interés corriente × 1,5"]
  },
  "accion": "Si tienes un crédito o una tarjeta, busca en tu contrato o en la hoja resumen la **CAE** y el **costo total**, y compara con la tasa mensual que te informaron. Si vas a pedir un crédito, cotiza al menos dos ofertas del mismo monto y plazo y elige por CAE y costo total. Revisa también la tasa máxima convencional vigente en cmfchile.cl.",
  "calculadoras": ["tasas", "credito"],
  "terminos": [
    {"es": "tasa real", "en": "real interest rate", "definicion": "Tasa descontada la inflación: crecimiento del poder de compra.", "ejemplo": "The real rate was negative last year."},
    {"es": "tasa anual efectiva", "en": "effective annual rate (EAR)", "definicion": "Tasa anual que incluye la capitalización de los períodos.", "ejemplo": "2% per month is a 26.8% effective annual rate."},
    {"es": "amortización", "en": "amortization / principal repayment", "definicion": "Parte de la cuota que reduce la deuda.", "ejemplo": "Early payments are mostly interest, not amortization."},
    {"es": "cuota", "en": "installment / payment", "definicion": "Pago periódico de un crédito (interés + amortización).", "ejemplo": "The monthly payment is $99,848."},
    {"es": "CAE", "en": "annual equivalent charge (similar to APR)", "definicion": "Carga Anual Equivalente: costo total del crédito expresado como tasa anual (Ley 20.555).", "ejemplo": "Compare loans by their APR and total cost."},
    {"es": "costo total del crédito", "en": "total cost of credit", "definicion": "Suma de todo lo que se paga por el crédito.", "ejemplo": "The total cost of credit was $3,979,166."},
    {"es": "tasa máxima convencional", "en": "maximum legal interest rate (usury cap)", "definicion": "Tope legal: interés corriente × 1,5 (Ley 18.010).", "ejemplo": "Charging above the cap is not allowed."}
  ],
  "fuentes": [
    {"titulo": "SERNAC — Criterios y ejemplo de cálculo de la CAE (crédito de $3.000.000, CAE 28,74 %)", "url": "https://www.sernac.cl/portal/617/articles-9192_archivo_01.pdf"},
    {"titulo": "SERNAC — Carga Anual Equivalente", "url": "https://sernac.cl/portal/604/w3-article-2928.html"},
    {"titulo": "CMF Educa — Interés máximo convencional", "url": "https://www.cmfchile.cl/educa/621/w3-propertyvalue-1188.html"},
    {"titulo": "CMF — Tasas de interés corriente y máxima convencional (publicación mensual)", "url": "https://www.cmfchile.cl/portal/estadisticas/617/w3-propertyvalue-29487.html"},
    {"titulo": "CMF Educa — Crédito de consumo", "url": "https://www.cmfchile.cl/educa/621/w3-propertyvalue-43579.html"},
    {"titulo": "CMF — Metodología de interés corriente y tasa máxima convencional", "url": "https://www.cmfchile.cl/portal/prensa/625/w4-article-102387.html"}
  ]
}
);
