window.CLASES_FIN = window.CLASES_FIN || []; window.CLASES_FIN.push(
{
  "id": 101,
  "etapa": 1,
  "formato": "leccion",
  "titulo": "El dinero pierde valor: inflación, IPC y UF",
  "subtitulo": "Por qué tu plata compra menos, cómo se mide y cómo te defiendes",
  "objetivo": "Entender qué es la inflación, calcular cuánto te afecta, leer el IPC como un economista y usar la UF a tu favor.",
  "gancho": "En agosto de 2022 la inflación en Chile llegó a **14,1 % en 12 meses**, la más alta en 30 años. Si ese año tenías **$1.000.000 guardado** en la cuenta corriente, no perdiste ni un peso… ¿o sí? Al terminar esta lección vas a saber cuánto perdiste exactamente, por qué los precios suben, cómo se mide y qué hacer para que no te pase en tu vida ni en tu negocio.",
  "leccion": [
    {"tipo": "predice", "pregunta": "Tienes $1.000.000 bajo el colchón. Durante el año los precios suben 10 %. A fin de año, ¿cuánto vale ese millón **en pesos de hoy** (lo que puedes comprar con él)?", "opciones": ["$1.000.000: no se movió", "$900.000", "Cerca de $909.091", "$1.100.000"], "respuestas": ["Cerca de $909.091"], "explicacion": "Sigues teniendo un millón de billetes, pero cada cosa cuesta 10 % más. Lo que compras equivale a 1.000.000 / 1,10 = $909.091. Mucha gente responde $900.000: en el paso siguiente verás por qué es un error."},
    {"tipo": "texto", "titulo": "La inflación no te quita billetes: te quita lo que compras con ellos", "texto": "**Inflación** es el alza **generalizada** (de muchos precios a la vez) y **sostenida** (en el tiempo) de los precios. No es que suba el tomate: sube el nivel de precios de la economía.\n\nSu efecto es que cae tu **poder adquisitivo**: con el mismo dinero compras menos. El monto en tu cuenta (valor **nominal**) no cambia, pero su valor **real** sí.", "diagrama": "poder_compra", "porque": "Todas las decisiones de dinero —ahorrar, endeudarte, fijar precios, pedir un aumento— se miden en valor real. Si solo miras el nominal, te engañas."},
    {"tipo": "ejemplo", "titulo": "¿Por qué se divide y no se resta?", "planteamiento": "Precios suben 10 %. ¿Cuánto vale hoy $1.000.000 de fin de año?", "pasos": [
      {"texto": "Piensa en una canasta que hoy cuesta $10.000. Con $1.000.000 compras **100 canastas**."},
      {"texto": "Con 10 % de inflación, la canasta pasa a costar $10.000 × 1,10 = **$11.000**.", "calculo": "10.000 × (1 + 0,10) = 11.000"},
      {"texto": "Con el mismo millón compras 1.000.000 / 11.000 = **90,9 canastas**: perdiste 9,1 canastas, no 10.", "calculo": "1.000.000 / 11.000 = 90,909 canastas"},
      {"texto": "En pesos de hoy: 90,909 canastas × $10.000 = **$909.091**. Es lo mismo que dividir el monto por (1 + inflación).", "calculo": "Poder adquisitivo = Monto / (1 + inflación)\n1.000.000 / 1,10 = 909.091"}
    ], "resultado": "Perdiste $90.909 de poder de compra (9,1 %), no $100.000. Restar el 10 % exagera la pérdida porque el 10 % se aplica sobre los precios, no sobre tu dinero."},
    {"tipo": "turno", "pregunta": "Tienes ${M} guardados sin intereses y la inflación del año es {pi} %. ¿Cuánto vale ese dinero en pesos de hoy al final del año? (redondea al peso)", "params": {"M": [500000, 3000000, 100000], "pi": [2, 15, 0.5]}, "formula": "M/(1+pi/100)", "tolRel": 0.002, "unidad": "$", "pista": "Divide el monto por (1 + inflación/100).", "explicacion": "{M} / (1 + {pi}/100) = ${=Math.round(M/(1+pi/100))}. Perdiste ${=Math.round(M-M/(1+pi/100))} de poder de compra."},
    {"tipo": "texto", "titulo": "¿Por qué suben los precios?", "texto": "Las causas principales:\n- **Demanda mayor que la oferta**: si la gente quiere comprar más de lo que la economía produce (por ejemplo, después de muchos retiros de fondos o bonos), los precios suben.\n- **Costos**: si sube el petróleo, el dólar o una materia prima, las empresas traspasan el costo a precios.\n- **Expectativas**: si todos esperan que los precios suban, piden más sueldo y suben precios por adelantado, y se cumple.\n\nEn Chile, el **Banco Central** tiene la misión de mantener la inflación **en torno a 3 % anual** (rango de 2 % a 4 %), mirando un horizonte de unos **dos años**. Su herramienta es la **tasa de política monetaria** (lo verás en la Etapa 3).", "porque": "Si entiendes la causa, puedes anticipar: cuando el dólar sube fuerte, en unos meses sube el precio de lo importado (envases, repuestos, tecnología)."},
    {"tipo": "pregunta", "pregunta": "La inflación anual bajó de 6 % a 4 %. ¿Qué pasó con los precios?", "opciones": ["Bajaron 2 %", "Siguen subiendo, pero más lento", "Volvieron al nivel del año pasado", "Bajaron 2 puntos porcentuales"], "respuestas": ["Siguen subiendo, pero más lento"], "pista": "La inflación es la VELOCIDAD a la que suben los precios, no su nivel.", "explicacion": "Que la inflación baje de 6 % a 4 % significa que los precios suben a menor velocidad. Para que bajen tendría que haber **deflación** (inflación negativa). Y ojo con el lenguaje: la inflación bajó **2 puntos porcentuales** (de 6 a 4), no '2 %'."},
    {"tipo": "texto", "titulo": "Cómo se mide: el IPC", "texto": "El **IPC (Índice de Precios al Consumidor)** lo calcula el **INE** cada mes. Sigue los precios de una **canasta** de bienes y servicios que consumen los hogares, y cada producto tiene un **peso (ponderación)** según cuánto gastan las familias en él; esos pesos salen de la **Encuesta de Presupuestos Familiares**.\n\nLa clave: el IPC es un **promedio ponderado**. Si sube mucho algo que pesa poco en el gasto, el IPC se mueve poco; si sube un poco algo que pesa mucho (como vivienda), el IPC se mueve bastante.", "diagrama": "canasta_ipc", "porque": "Por eso 'tu' inflación puede ser distinta a la oficial: si gastas más que el promedio en alimentos y los alimentos suben más, tu costo de vida sube más que el IPC."},
    {"tipo": "ejemplo", "titulo": "Calcular el IPC de una canasta", "planteamiento": "Canasta simplificada: alimentos pesa 30 % y subió 8 %; transporte pesa 20 % y subió 5 %; vivienda pesa 50 % y subió 2 %. ¿Cuánto fue la inflación de la canasta?", "pasos": [
      {"texto": "Cada grupo aporta su **peso × su variación**.", "calculo": "Alimentos: 0,30 × 8 % = 2,4 puntos\nTransporte: 0,20 × 5 % = 1,0 punto\nVivienda: 0,50 × 2 % = 1,0 punto"},
      {"texto": "La inflación de la canasta es la **suma de los aportes**.", "calculo": "2,4 + 1,0 + 1,0 = 4,4 %"},
      {"texto": "Fíjate: alimentos subió 8 % pero el total fue 4,4 %, porque vivienda —que pesa la mitad— subió poco."}
    ], "resultado": "Inflación de la canasta = 4,4 %."},
    {"tipo": "turno", "pregunta": "Misma canasta (alimentos 30 %, transporte 20 %, vivienda 50 %). Este mes alimentos subió {a} %, transporte {t} % y vivienda {v} %. ¿Inflación de la canasta? (%, 2 decimales)", "params": {"a": [0, 12, 0.5], "t": [-3, 10, 0.5], "v": [0, 6, 0.5]}, "formula": "0.3*a+0.2*t+0.5*v", "tolerancia": 0.02, "unidad": "%", "pista": "Suma: 0,30 × alimentos + 0,20 × transporte + 0,50 × vivienda.", "explicacion": "0,30 × {a} + 0,20 × {t} + 0,50 × {v} = {=0.3*a+0.2*t+0.5*v} %."},
    {"tipo": "texto", "titulo": "Tres cifras que no hay que confundir", "texto": "El INE publica el IPC alrededor del **día 8** de cada mes y se informan tres cifras:\n- **Variación mensual**: cuánto subieron los precios ese mes (ej.: +0,4 %).\n- **Acumulada en el año**: desde diciembre del año anterior hasta ese mes.\n- **En 12 meses**: comparada con el mismo mes del año pasado. Es la que se usa para decir 'la inflación anual es X'.\n\nY una regla técnica: las variaciones **se componen, no se suman**. Para acumular, multiplicas los factores (1 + variación).", "porque": "En agosto de 2022 la inflación en 12 meses fue 14,1 % y la acumulada en el año 9,9 %. Mismo mes, dos cifras distintas: si las confundes, te equivocas por mucho."},
    {"tipo": "ejemplo", "titulo": "Acumular tres meses de IPC", "planteamiento": "IPC de julio +0,4 %, agosto +0,6 %, septiembre +0,3 %. ¿Inflación acumulada del trimestre?", "pasos": [
      {"texto": "Convierte cada porcentaje en factor: 1 + variación/100.", "calculo": "1,004 · 1,006 · 1,003"},
      {"texto": "Multiplica los factores.", "calculo": "1,004 × 1,006 × 1,003 = 1,013054"},
      {"texto": "Resta 1 y pásalo a porcentaje.", "calculo": "1,013054 − 1 = 0,013054 → 1,31 %"}
    ], "resultado": "Acumulada = 1,31 % (sumar daría 1,30 %: con cifras chicas la diferencia es pequeña; con 12 meses de inflación alta es grande)."},
    {"tipo": "turno", "pregunta": "IPC de tres meses seguidos: +{a} %, +{b} % y +{c} %. ¿Inflación acumulada? (%, 2 decimales)", "params": {"a": [0.1, 1.5, 0.1], "b": [0.1, 1.5, 0.1], "c": [0.1, 1.5, 0.1]}, "formula": "((1+a/100)*(1+b/100)*(1+c/100)-1)*100", "tolerancia": 0.011, "unidad": "%", "pista": "Multiplica (1 + a/100)·(1 + b/100)·(1 + c/100), resta 1 y multiplica por 100.", "explicacion": "({=1+a/100}) × ({=1+b/100}) × ({=1+c/100}) − 1 = {=((1+a/100)*(1+b/100)*(1+c/100)-1)*100} %."},
    {"tipo": "texto", "titulo": "El problema de los contratos largos… y la solución chilena: la UF", "texto": "Imagina un crédito hipotecario a 20 años en pesos con inflación alta: el banco recibiría pesos que valen cada vez menos, así que nadie prestaba a largo plazo. Para resolverlo, en **1967** (DS N°40 de Hacienda) se creó la **Unidad de Fomento (UF)**: una unidad de cuenta que **se reajusta según la inflación**.\n\nHoy la calcula el **Banco Central**: cambia **cada día**, desde el **día 10** de un mes hasta el **día 9** del siguiente, repartiendo (con una tasa diaria geométrica) la variación del **IPC del mes anterior**.", "diagrama": "uf_linea", "porque": "La UF mantiene el valor REAL de un contrato. Por eso se usa en arriendos, créditos hipotecarios, planes de salud, colegios y contratos de largo plazo."},
    {"tipo": "ejemplo", "titulo": "Tu arriendo en UF", "planteamiento": "Pagas un arriendo de 12 UF. Hoy la UF vale $39.500. El IPC del mes pasado fue +0,5 %. ¿Cuánto pagas hoy y cuánto pagarás en un mes?", "pasos": [
      {"texto": "Hoy: cantidad de UF × valor de la UF.", "calculo": "12 × 39.500 = $474.000"},
      {"texto": "En un mes la UF habrá subido lo que subió el IPC (0,5 %).", "calculo": "39.500 × 1,005 = $39.697,5"},
      {"texto": "El arriendo en pesos sube lo mismo.", "calculo": "12 × 39.697,5 = $476.370"}
    ], "resultado": "Pagas $2.370 más en pesos, pero el dueño recibe exactamente el mismo valor real. Tú pagas lo mismo 'en canastas'."},
    {"tipo": "turno", "pregunta": "Un plan de salud cuesta {U} UF. Si la UF vale ${V}, ¿cuánto pagas en pesos? (redondea)", "params": {"U": [1.5, 8, 0.5], "V": [38000, 41000, 50]}, "formula": "U*V", "tolerancia": 1, "unidad": "$", "pista": "Pesos = cantidad de UF × valor de la UF.", "explicacion": "{U} × {V} = ${=Math.round(U*V)}."},
    {"tipo": "pregunta", "pregunta": "Tienes un crédito hipotecario en UF y llega un año de inflación alta. ¿Qué pasa con tu deuda?", "opciones": ["Medida en pesos aumenta, pero en términos reales sigue igual", "Disminuye porque la inflación 'licúa' la deuda", "No cambia en pesos", "El banco pierde dinero"], "respuestas": ["Medida en pesos aumenta, pero en términos reales sigue igual"], "pista": "La UF sube con la inflación.", "explicacion": "Tu deuda en UF no cambia, pero cada UF vale más pesos: la deuda en pesos crece al ritmo de la inflación. Al banco no le afecta: recibe el mismo valor real. Si tu sueldo no sube con la inflación, ese crédito te pesará más."},
    {"tipo": "pregunta", "pregunta": "¿Quién se protege con la UF?", "opciones": ["Quien RECIBE los pagos (acreedor, arrendador, vendedor)", "Quien PAGA (deudor, arrendatario)", "Nadie, es neutral", "Solo el Banco Central"], "respuestas": ["Quien RECIBE los pagos (acreedor, arrendador, vendedor)"], "explicacion": "La UF asegura que quien recibe un pago futuro no pierda poder adquisitivo. Para quien paga es neutral en términos reales, pero solo si sus ingresos también suben con la inflación."},
    {"tipo": "calc", "titulo": "Experimenta con la inflación", "tarea": "Pon **inflación 4 %** y **10 años** en la calculadora. Mira cuánto pierde $1.000.000 guardado sin intereses. Después prueba con 14,1 % y 1 año (como en 2022).", "calc": "inflacion_uf"},
    {"tipo": "pregunta", "pregunta": "Según la calculadora, con una inflación de 4 % anual durante 10 años, ¿qué porcentaje de su poder de compra pierde el dinero guardado sin intereses? (aprox., en %)", "respuesta": 32.4, "tolerancia": 0.6, "como": "numero", "unidad": "%", "pista": "Poder de compra = 1 / 1,04¹⁰. La pérdida es 1 − eso.", "explicacion": "1 / 1,04¹⁰ = 0,676 → pierde 32,4 %. Una inflación 'baja' de 4 % te quita casi un tercio en 10 años. Por eso el dinero ocioso es caro."},
    {"tipo": "turno", "pregunta": "Este año tu sueldo subió {s} % y la inflación fue {pi} %. ¿Cuánto cambió tu sueldo en términos REALES? (%, 2 decimales, negativo si perdiste)", "params": {"s": [2, 10, 0.5], "pi": [2, 12, 0.5]}, "formula": "((1+s/100)/(1+pi/100)-1)*100", "tolerancia": 0.02, "unidad": "%", "pista": "Real = (1 + sueldo) / (1 + inflación) − 1.", "explicacion": "(1 + {s}/100) / (1 + {pi}/100) − 1 = {=((1+s/100)/(1+pi/100)-1)*100} %. Aproximado: {s} − {pi} = {=s-pi} puntos."},
    {"tipo": "reflexion", "consigna": "Un amigo te dice: 'Mi arriendo está en UF y cada mes me cobran un poco más; me están estafando'. Explícale por qué sube, quién calcula ese valor y si en realidad está pagando más.", "modelo": "No es una estafa: la UF es una unidad que se reajusta con la inflación. Cada mes el INE publica el IPC y, con ese dato, el Banco Central calcula la UF para cada día entre el 10 de un mes y el 9 del siguiente. Si hubo inflación, la UF sube un poco cada día y tu arriendo en pesos también. Pero como los precios en general subieron lo mismo, en términos reales pagas lo mismo: el dueño solo mantiene el valor de lo que recibe. El problema aparece si tu sueldo no sube con la inflación.", "claves": ["La UF se reajusta con la inflación (IPC del mes anterior)", "La calcula el Banco Central, día a día del 10 al 9", "En pesos sube, pero en valor real se paga lo mismo", "El riesgo es que el ingreso no suba con la inflación"]},
    {"tipo": "resumen", "puntos": ["La inflación es el alza **generalizada y sostenida** de precios; reduce tu **poder adquisitivo**.", "Valor real = monto / (1 + inflación): **se divide, no se resta**.", "El **IPC** (INE) es un promedio **ponderado** de una canasta; tu inflación personal puede ser distinta.", "Mensual, acumulada en el año y en 12 meses son cifras distintas; las variaciones **se componen**.", "El **Banco Central** busca una inflación en torno a **3 %** (rango 2–4 %).", "La **UF** (1967) se reajusta día a día con el IPC del mes anterior y protege el **valor real** de los contratos."]}
  ],
  "caso": {
    "titulo": "Caso práctico: la inflación golpea tu negocio de jugos",
    "contexto": "Vendes jugo natural de naranja en botellas de 1 L a **$2.500**. Tu costo por botella (ejemplo ilustrativo) es: naranjas **$1.200**, envase **$250**, etiqueta y tapa **$80**, transporte **$170**. Total **$1.700**, margen **$800 (32 %)**. Este año la naranja subió **12 %**, el envase **5 %**, la etiqueta **0 %** y el transporte **8 %**. La inflación general fue **4 %**.",
    "pasos": [
      {"tipo": "predice", "pregunta": "Antes de calcular: ¿cuánto crees que subió tu costo total por botella?", "opciones": ["Cerca de 4 % (como la inflación)", "Cerca de 6 % (promedio simple de 12, 5, 0 y 8)", "Cerca de 10 %", "12 %"], "respuestas": ["Cerca de 10 %"], "explicacion": "Tu costo sube según TU canasta de costos, no según el IPC. La naranja pesa el 70 % de tu costo y subió 12 %: eso arrastra el total a ~10 %."},
      {"tipo": "ejemplo", "titulo": "Tu propio 'IPC de costos'", "planteamiento": "Calcula el nuevo costo por botella.", "pasos": [
        {"texto": "Aplica a cada ítem su alza.", "calculo": "Naranjas: 1.200 × 1,12 = 1.344\nEnvase: 250 × 1,05 = 262,5\nEtiqueta: 80 × 1,00 = 80\nTransporte: 170 × 1,08 = 183,6"},
        {"texto": "Suma.", "calculo": "1.344 + 262,5 + 80 + 183,6 = $1.870,1"},
        {"texto": "Variación del costo total.", "calculo": "1.870,1 / 1.700 − 1 = 10,0 %"}
      ], "resultado": "Tu costo subió 10,0 %, más del doble que la inflación general (4 %)."},
      {"tipo": "pregunta", "pregunta": "Si mantienes el precio en $2.500, ¿cuál es tu nuevo margen por botella en pesos? (redondea)", "respuesta": 630, "tolerancia": 1, "como": "numero", "unidad": "$", "explicacion": "2.500 − 1.870,1 = $629,9 ≈ $630. Tu margen cae de 32 % a 25,2 %: vendiendo lo mismo, ganas 21 % menos."},
      {"tipo": "pregunta", "pregunta": "¿A qué precio deberías vender para mantener tu margen de 32 % sobre el precio? (redondea a la decena)", "respuesta": 2750, "tolerancia": 10, "como": "numero", "unidad": "$", "pista": "Si el margen es 32 % del precio, el costo es el 68 %: precio = costo / 0,68.", "explicacion": "1.870,1 / 0,68 = $2.750. Subir a $2.750 (+10 %) mantiene el porcentaje de margen."},
      {"tipo": "pregunta", "pregunta": "Alternativa: mantener tu margen en pesos REALES (los $800 ajustados por la inflación de 4 %). ¿Qué precio necesitas? (redondea a la decena)", "respuesta": 2700, "tolerancia": 10, "como": "numero", "unidad": "$", "pista": "Margen real = 800 × 1,04. Precio = nuevo costo + margen real.", "explicacion": "800 × 1,04 = 832 → 1.870,1 + 832 = $2.702 ≈ $2.700. Es el mínimo para no empobrecerte en términos reales."},
      {"tipo": "pregunta", "pregunta": "Una cafetería te ofrece un contrato por 12 meses: 200 botellas al mes. ¿Qué cláusula te conviene más como vendedor?", "opciones": ["Precio fijado en UF (o reajustable por IPC)", "Precio fijo en pesos por 12 meses", "Da lo mismo", "Precio en dólares"], "respuestas": ["Precio fijado en UF (o reajustable por IPC)"], "explicacion": "Con precio fijo en pesos y 4 % de inflación, el último mes tu botella de $2.500 vale en realidad 2.500 / 1,04 = $2.404 de hoy. En UF, el precio se ajusta solo. Tú recibes los pagos: la UF te protege."},
      {"tipo": "reflexion", "consigna": "Con lo que calculaste, ¿qué decisión tomarías con el precio y por qué? Menciona tu costo, tu margen y la inflación.", "modelo": "Mi costo subió 10 %, mucho más que la inflación general de 4 %, porque la naranja pesa el 70 % del costo. Si no subo el precio, mi margen baja de 32 % a 25 %. Subiría el precio a entre $2.700 (para mantener el margen real) y $2.750 (para mantener el margen en %), idealmente en etapas y comunicándolo. En contratos con clientes fijos pondría el precio en UF o reajustable por IPC.", "claves": ["El costo subió ~10 %, no 4 %", "Sin subir precio, el margen cae de 32 % a ~25 %", "Rango de precio razonable: $2.700–$2.750", "Contratos largos: precio en UF o reajustable"]}
    ]
  },
  "desafio": [
    {"tipo": "numero", "pregunta": "Tienes ${M} sin intereses y la inflación del año es {pi} %. ¿Cuánto vale en pesos de hoy al final del año? (redondea)", "params": {"M": [500000, 5000000, 100000], "pi": [2, 15, 0.5]}, "formula": "M/(1+pi/100)", "tolRel": 0.002, "unidad": "$", "explicacion": "{M} / (1 + {pi}/100) = ${=Math.round(M/(1+pi/100))}."},
    {"tipo": "numero", "pregunta": "Un producto pasó de ${P0} a ${=Math.round(P0*(1+d/100))}. ¿Variación porcentual? (%, 1 decimal, negativa si bajó)", "params": {"P0": [1000, 9000, 100], "d": [-20, 30, 1]}, "formula": "(Math.round(P0*(1+d/100))-P0)/P0*100", "tolerancia": 0.06, "unidad": "%", "explicacion": "(precio final − inicial) / inicial × 100 = {=(Math.round(P0*(1+d/100))-P0)/P0*100} %."},
    {"tipo": "numero", "pregunta": "IPC de tres meses: +{a} %, +{b} % y +{c} %. ¿Inflación acumulada? (%, 2 decimales)", "params": {"a": [0.1, 1.5, 0.1], "b": [0.1, 1.5, 0.1], "c": [0.1, 1.5, 0.1]}, "formula": "((1+a/100)*(1+b/100)*(1+c/100)-1)*100", "tolerancia": 0.011, "unidad": "%", "explicacion": "Se multiplican los factores: {=((1+a/100)*(1+b/100)*(1+c/100)-1)*100} %."},
    {"tipo": "numero", "pregunta": "Canasta: alimentos (peso 30 %) subió {a} %, transporte (20 %) {t} % y vivienda (50 %) {v} %. ¿Inflación de la canasta? (%, 2 decimales)", "params": {"a": [0, 12, 0.5], "t": [-3, 10, 0.5], "v": [0, 6, 0.5]}, "formula": "0.3*a+0.2*t+0.5*v", "tolerancia": 0.02, "unidad": "%", "explicacion": "Promedio ponderado: {=0.3*a+0.2*t+0.5*v} %."},
    {"tipo": "numero", "pregunta": "Un arriendo de {U} UF con la UF a ${V}. ¿Cuánto pagas en pesos? (redondea)", "params": {"U": [5, 20, 0.5], "V": [38000, 41000, 50]}, "formula": "U*V", "tolerancia": 1, "unidad": "$", "explicacion": "{U} × {V} = ${=Math.round(U*V)}."},
    {"tipo": "numero", "pregunta": "Hoy la UF vale ${V} y el IPC del mes pasado fue +{ipc} %. ¿Cuánto valdrá aproximadamente la UF el día 9 del próximo mes? (redondea al peso)", "params": {"V": [38000, 41000, 50], "ipc": [0.1, 1, 0.1]}, "formula": "V*(1+ipc/100)", "tolerancia": 2, "unidad": "$", "explicacion": "Entre el 10 y el 9 la UF acumula la variación del IPC: {V} × (1 + {ipc}/100) = ${=Math.round(V*(1+ipc/100))}."},
    {"tipo": "numero", "pregunta": "Tu sueldo subió {s} % y la inflación fue {pi} %. ¿Variación REAL de tu sueldo? (%, 2 decimales)", "params": {"s": [2, 10, 0.5], "pi": [2, 12, 0.5]}, "formula": "((1+s/100)/(1+pi/100)-1)*100", "tolerancia": 0.02, "unidad": "%", "explicacion": "(1 + {s}/100)/(1 + {pi}/100) − 1 = {=((1+s/100)/(1+pi/100)-1)*100} %."},
    {"tipo": "alternativas", "pregunta": "La inflación en 12 meses bajó de 8 % a 5 %. ¿Qué es correcto?", "opciones": ["Los precios siguen subiendo, pero más lento; bajó 3 puntos porcentuales", "Los precios bajaron 3 %", "Hubo deflación", "La UF empezó a bajar"], "respuestas": ["Los precios siguen subiendo, pero más lento; bajó 3 puntos porcentuales"], "explicacion": "Inflación más baja ≠ precios más bajos. La diferencia entre dos porcentajes se dice en puntos porcentuales."},
    {"tipo": "alternativas", "pregunta": "Gastas proporcionalmente mucho más que el promedio en alimentos, y este año los alimentos subieron más que el resto. ¿Qué pasa con tu costo de vida?", "opciones": ["Sube más que el IPC oficial", "Sube igual que el IPC", "Sube menos que el IPC", "No se puede saber nada"], "respuestas": ["Sube más que el IPC oficial"], "explicacion": "El IPC usa los pesos de un hogar promedio. Si tu canasta pesa más lo que más subió, tu inflación personal es mayor."},
    {"tipo": "alternativas", "pregunta": "¿Quién calcula el valor de la UF y con qué dato?", "opciones": ["El Banco Central, con el IPC que publica el INE", "El INE, con el dólar", "El SII, con el sueldo mínimo", "Los bancos, con sus tasas"], "respuestas": ["El Banco Central, con el IPC que publica el INE"], "explicacion": "El SII también publica el valor, pero lo calcula el Banco Central."},
    {"tipo": "alternativas", "pregunta": "Vas a firmar un arriendo a 3 años como ARRENDADOR (tú recibes el pago). Se espera inflación alta. ¿Qué te conviene?", "opciones": ["Arriendo en UF", "Arriendo fijo en pesos por 3 años", "Da lo mismo", "Arriendo con pago adelantado de 3 años sin descuento"], "respuestas": ["Arriendo en UF"], "explicacion": "Quien recibe pagos futuros se protege con la UF; con pesos fijos, la inflación se come el valor real del arriendo."},
    {"tipo": "numero", "pregunta": "Si la inflación se mantiene en {pi} % anual, ¿qué porcentaje del poder de compra pierde el dinero guardado sin intereses en {n} años? (%, 1 decimal)", "params": {"pi": [2, 8, 0.5], "n": [3, 15, 1]}, "formula": "(1-1/Math.pow(1+pi/100,n))*100", "tolerancia": 0.15, "unidad": "%", "explicacion": "1 − 1/(1 + {pi}/100)^{n} = {=(1-1/Math.pow(1+pi/100,n))*100} %."},
    {"tipo": "alternativas", "pregunta": "¿Cuál es la meta de inflación del Banco Central de Chile?", "opciones": ["En torno a 3 % anual (rango 2–4 %) en un horizonte de unos 2 años", "0 %: que los precios no suban nunca", "La misma que Estados Unidos", "No tiene meta"], "respuestas": ["En torno a 3 % anual (rango 2–4 %) en un horizonte de unos 2 años"], "explicacion": "Una inflación baja y estable (no cero) es la meta de la mayoría de los bancos centrales."},
    {"tipo": "escritura", "pregunta": "En 60+ palabras: explícale a un cliente de tu negocio por qué subiste el precio de la botella, usando los conceptos de esta clase.", "minPalabras": 60, "obligatorias": ["inflación", "costo", "margen", "precio"]}
  ],
  "repaso": [
    {"tipo": "numero", "etiqueta": "Poder adquisitivo", "pregunta": "${M} guardados sin intereses, inflación {pi} %. ¿Valor en pesos de hoy al final del año? (redondea)", "params": {"M": [500000, 3000000, 100000], "pi": [2, 12, 0.5]}, "formula": "M/(1+pi/100)", "tolRel": 0.002, "unidad": "$", "explicacion": "Se divide: {M} / (1 + {pi}/100) = ${=Math.round(M/(1+pi/100))}."},
    {"tipo": "alternativas", "etiqueta": "Inflación que baja", "pregunta": "Si la inflación baja de 7 % a 3 %, los precios…", "opciones": ["siguen subiendo, más lento", "bajan 4 %", "vuelven atrás", "bajan 4 puntos porcentuales"], "respuestas": ["siguen subiendo, más lento"], "explicacion": "La inflación es la velocidad del alza; para que bajen haría falta deflación."},
    {"tipo": "numero", "etiqueta": "Acumular IPC", "pregunta": "IPC: +{a} % y luego +{b} %. ¿Acumulada? (%, 2 decimales)", "params": {"a": [0.1, 2, 0.1], "b": [0.1, 2, 0.1]}, "formula": "((1+a/100)*(1+b/100)-1)*100", "tolerancia": 0.011, "unidad": "%", "explicacion": "(1 + {a}/100)(1 + {b}/100) − 1 = {=((1+a/100)*(1+b/100)-1)*100} %: se componen, no se suman."},
    {"tipo": "numero", "etiqueta": "IPC ponderado", "pregunta": "Dos grupos: A pesa {w} % y subió {x} %; B pesa el resto y subió {y} %. ¿Inflación total? (%, 2 decimales)", "params": {"w": [20, 80, 5], "x": [0, 10, 0.5], "y": [0, 10, 0.5]}, "formula": "(w*x+(100-w)*y)/100", "tolerancia": 0.02, "unidad": "%", "explicacion": "{w} % × {x} + {=100-w} % × {y} = {=(w*x+(100-w)*y)/100} %."},
    {"tipo": "numero", "etiqueta": "UF a pesos", "pregunta": "{U} UF con la UF a ${V}. ¿En pesos? (redondea)", "params": {"U": [1, 15, 0.5], "V": [38000, 41000, 50]}, "formula": "U*V", "tolerancia": 1, "unidad": "$", "explicacion": "{U} × {V} = ${=Math.round(U*V)}."},
    {"tipo": "alternativas", "etiqueta": "Quién se protege con la UF", "pregunta": "La UF protege principalmente a…", "opciones": ["quien recibe pagos futuros", "quien paga", "al Banco Central", "a nadie"], "respuestas": ["quien recibe pagos futuros"], "explicacion": "Mantiene el valor real de lo que se recibe."},
    {"tipo": "alternativas", "etiqueta": "Cómo se calcula la UF", "pregunta": "La UF cambia…", "opciones": ["cada día, del 10 al 9, con el IPC del mes anterior", "una vez al mes, el día 1", "cada día, según el dólar", "una vez al año"], "respuestas": ["cada día, del 10 al 9, con el IPC del mes anterior"], "explicacion": "La calcula el Banco Central con una tasa diaria geométrica."},
    {"tipo": "numero", "etiqueta": "Sueldo real", "pregunta": "Sueldo +{s} %, inflación {pi} %. ¿Variación real? (%, 2 decimales)", "params": {"s": [1, 12, 0.5], "pi": [1, 12, 0.5]}, "formula": "((1+s/100)/(1+pi/100)-1)*100", "tolerancia": 0.02, "unidad": "%", "explicacion": "(1 + {s}/100)/(1 + {pi}/100) − 1 = {=((1+s/100)/(1+pi/100)-1)*100} %."},
    {"tipo": "alternativas", "etiqueta": "Tu costo vs. el IPC", "pregunta": "Tu principal insumo (70 % de tu costo) sube 12 % y el IPC sube 4 %. Tu costo total sube…", "opciones": ["bastante más que 4 %", "4 %", "menos que 4 %", "12 % exacto"], "respuestas": ["bastante más que 4 %"], "explicacion": "Tu costo se mueve con TU canasta de costos: 0,70 × 12 % ya son 8,4 puntos."},
    {"tipo": "alternativas", "etiqueta": "Meta del Banco Central", "pregunta": "El Banco Central de Chile busca una inflación de…", "opciones": ["en torno a 3 % anual", "0 %", "10 %", "la que fije el gobierno cada año"], "respuestas": ["en torno a 3 % anual"], "explicacion": "Rango 2–4 %, horizonte de unos dos años."}
  ],
  "ficha": {
    "ideas": ["**Inflación**: alza generalizada y sostenida de precios → cae el poder adquisitivo.", "**Nominal vs. real**: el monto no cambia; lo que compras sí.", "**IPC** (INE, ~día 8): promedio **ponderado** de una canasta (Encuesta de Presupuestos Familiares).", "Cifras: **mensual**, **acumulada en el año**, **en 12 meses**. Se **componen**.", "**Banco Central**: meta ~3 % (rango 2–4 %), horizonte ~2 años.", "**UF** (1967): se reajusta cada día del 10 al 9 con el IPC del mes anterior; protege a quien recibe pagos."],
    "formulas": ["Variación % = (P₁ − P₀) / P₀ × 100", "Valor real = Monto / (1 + inflación)", "Pérdida de poder de compra en n años = 1 − 1 / (1 + π)ⁿ", "IPC de una canasta = Σ (peso × variación)", "Acumulada = (1 + v₁)(1 + v₂)… − 1", "Pesos = UF × valor UF", "Variación real ≈ nominal − inflación  (exacta: (1+n)/(1+π) − 1)"]
  },
  "accion": "Busca el valor de la UF de hoy en **sii.cl** o **bcentral.cl** y calcula cuánto pagas en pesos por algo que tengas en UF (arriendo, plan de salud, seguro). Luego revisa cuánto dinero tienes en la cuenta corriente sin intereses y calcula cuánto poder de compra pierde en un año con una inflación de 4 %.",
  "calculadoras": ["inflacion_uf"],
  "terminos": [
    {"es": "inflación", "en": "inflation", "definicion": "Alza generalizada y sostenida del nivel de precios.", "ejemplo": "Inflation reduces purchasing power."},
    {"es": "poder adquisitivo", "en": "purchasing power", "definicion": "Cantidad de bienes y servicios que puedes comprar con tu dinero.", "ejemplo": "High inflation erodes purchasing power."},
    {"es": "valor real", "en": "real value", "definicion": "Valor de un monto descontada la inflación (en 'pesos de hoy').", "ejemplo": "In real terms, my salary fell."},
    {"es": "IPC", "en": "CPI (consumer price index)", "definicion": "Índice de Precios al Consumidor del INE: promedio ponderado de los precios de una canasta.", "ejemplo": "The CPI rose 0.4% in March."},
    {"es": "ponderación", "en": "weight", "definicion": "Importancia de cada producto en la canasta según el gasto de los hogares.", "ejemplo": "Housing has a large weight in the CPI."},
    {"es": "deflación", "en": "deflation", "definicion": "Baja generalizada y sostenida de los precios.", "ejemplo": "Deflation is rare."},
    {"es": "punto porcentual", "en": "percentage point", "definicion": "Diferencia entre dos porcentajes (de 6 % a 4 % = −2 pp).", "ejemplo": "Inflation fell two percentage points."},
    {"es": "UF", "en": "inflation-indexed unit of account (UF)", "definicion": "Unidad de Fomento: se reajusta cada día con el IPC; la calcula el Banco Central.", "ejemplo": "Chilean mortgages are in UF."}
  ],
  "fuentes": [
    {"titulo": "Banco Central de Chile — Metodología de la UF", "url": "https://si3.bcentral.cl/estadisticas/Principal1/Metodologias/EMF/UF.pdf"},
    {"titulo": "Banco Central de Chile — Política monetaria (meta de inflación)", "url": "https://www.bcentral.cl/es/areas/politica-monetaria"},
    {"titulo": "INE — Boletín IPC agosto 2022 (14,1 % en 12 meses)", "url": "https://www.ine.cl/docs/default-source/índice-de-precios-al-consumidor/boletines/español/2022/boletin-indice-de-precios-al-consumidor-ipc-agosto-2022.pdf"},
    {"titulo": "CMF Educa — ¿La Unidad de Fomento es dinero?", "url": "https://www.cmfchile.cl/educa/600/w3-article-27474.html"},
    {"titulo": "Chócale — Origen de la UF (1967, DS 40 de Hacienda)", "url": "https://chocale.cl/2023/05/unidad-de-fomento-uf-origen-historia-unidad-monetaria/"}
  ]
}
);
