window.CLASES_FIN = window.CLASES_FIN || []; window.CLASES_FIN.push(
{
  "id": 102,
  "etapa": 1,
  "formato": "leccion",
  "titulo": "El tiempo vale dinero: interés compuesto y valor presente",
  "subtitulo": "Por qué empezar antes gana, cuánto vale hoy un pago futuro y cómo crece una deuda",
  "objetivo": "Calcular cuánto crece el dinero (simple y compuesto), cuánto vale hoy un pago futuro, cuánto juntas ahorrando todos los meses, y usarlo para decidir.",
  "gancho": "Dos amigos ahorran $50.000 al mes (= $600.000 al año) con una rentabilidad de 7 % anual (ejemplo ilustrativo). **Camila** ahorra desde los 25 hasta los 35 años y **nunca más** aporta. **Diego** empieza a los 35 y aporta **todos los años hasta los 65**. Camila pone $6 millones; Diego, $18 millones. **¿Quién tiene más a los 65?** Al final de esta lección lo vas a poder calcular, y vas a entender la idea más poderosa de las finanzas: **el tiempo trabaja para ti (o en tu contra)**.",
  "leccion": [
    {"tipo": "predice", "pregunta": "Depositas $1.000.000 al 10 % anual y **no retiras los intereses**. ¿Cuánto tienes al cabo de 2 años?", "opciones": ["$1.200.000", "$1.210.000", "$1.100.000", "$1.020.000"], "respuestas": ["$1.210.000"], "explicacion": "El primer año ganas $100.000 → $1.100.000. El segundo año ganas 10 % sobre $1.100.000, o sea $110.000 → **$1.210.000**. Los $10.000 extra son **interés sobre interés**: eso es el interés compuesto."},
    {"tipo": "texto", "titulo": "El interés: el precio del tiempo", "texto": "El **interés** es lo que paga quien usa dinero ajeno a quien se lo presta. Si ahorras, es tu **ganancia**; si debes, es tu **costo**.\n\n¿Por qué existe? Porque quien presta renuncia a usar su dinero hoy, y pide que le compensen tres cosas:\n- **Esperar** (preferimos tener las cosas antes).\n- **La inflación** (lo que viste en la clase 1: el dinero pierde valor).\n- **El riesgo** de que no le paguen.\n\nPor eso un crédito de consumo cobra más que un hipotecario (más riesgo), y por eso las tasas suben cuando sube la inflación.", "porque": "Esta idea es la base de todo lo que viene: créditos, ahorro, bonos, valorar una empresa. Siempre es la misma pregunta: ¿cuánto vale el dinero en distintos momentos?"},
    {"tipo": "texto", "titulo": "Simple vs. compuesto", "texto": "- **Interés simple**: los intereses se calculan siempre sobre el **capital inicial**. Crece en línea recta.\n- **Interés compuesto**: los intereses se **suman al capital** y el período siguiente también ganan intereses. Crece cada vez más rápido.\n\nCasi todo en la vida real es compuesto: depósitos renovados, fondos, AFP… y también las **deudas que no pagas**.", "diagrama": "simple_compuesto", "porque": "A 5 años la diferencia es chica; a 30 años, el compuesto multiplica tu dinero 7,6 veces y el simple solo 3,1 veces. El ingrediente secreto no es la tasa: es el **tiempo**."},
    {"tipo": "ejemplo", "titulo": "$1.000.000 al 6 % durante 3 años", "planteamiento": "Compara cuánto tienes con interés simple y con interés compuesto.", "pasos": [
      {"texto": "**Simple**: cada año ganas 6 % de $1.000.000 = $60.000. En 3 años, $180.000.", "calculo": "VF = VP × (1 + r × n)\n1.000.000 × (1 + 0,06 × 3) = $1.180.000"},
      {"texto": "**Compuesto**: cada año multiplicas por 1,06 lo que ya tienes.", "calculo": "Año 1: 1.000.000 × 1,06 = 1.060.000\nAño 2: 1.060.000 × 1,06 = 1.123.600\nAño 3: 1.123.600 × 1,06 = 1.191.016"},
      {"texto": "Es lo mismo que elevar 1,06 a la cantidad de años.", "calculo": "VF = VP × (1 + r)ⁿ\n1.000.000 × 1,06³ = $1.191.016"}
    ], "resultado": "Compuesto: $1.191.016, $11.016 más que el simple. En 3 años es poco; en 30 años, la diferencia es enorme."},
    {"tipo": "turno", "pregunta": "Inviertes ${VP} a {r} % anual compuesto durante {n} años. ¿Cuánto tienes al final? (redondea al peso)", "params": {"VP": [500000, 5000000, 100000], "r": [3, 12, 0.5], "n": [2, 15, 1]}, "formula": "VP*Math.pow(1+r/100,n)", "tolRel": 0.001, "unidad": "$", "pista": "VF = VP × (1 + r/100) elevado a n.", "explicacion": "{VP} × (1 + {r}/100)^{n} = ${=Math.round(VP*Math.pow(1+r/100,n))}."},
    {"tipo": "pregunta", "pregunta": "Con una rentabilidad de 7 % anual, ¿cuántas veces se multiplica tu dinero en 30 años?", "opciones": ["Unas 3 veces (7 % × 30 = 210 %)", "Unas 7,6 veces", "Unas 2 veces", "Unas 30 veces"], "respuestas": ["Unas 7,6 veces"], "pista": "Calcula 1,07 elevado a 30.", "explicacion": "1,07³⁰ = **7,61**. Pensar '7 % × 30 años = 210 %' es pensar en interés simple. Con interés compuesto, $1.000.000 se convierte en $7.612.255."},
    {"tipo": "texto", "titulo": "La regla del 72: calcular de cabeza", "texto": "¿En cuántos años se **duplica** tu dinero? Divide **72 por la tasa anual** (en %).\n- Al 6 %: 72 / 6 = **12 años**.\n- Al 8 %: 72 / 8 = **9 años**.\n- Al revés: para duplicar en 6 años necesitas 72 / 6 = **12 % anual**.\n\nEs una aproximación muy buena entre 4 % y 15 %. Sirve también para deudas e inflación: con 7 % de inflación, los precios se duplican en unos 10 años.", "porque": "Te permite evaluar en segundos una promesa de rentabilidad o el costo de una deuda, sin calculadora."},
    {"tipo": "turno", "pregunta": "Según la regla del 72, ¿en cuántos años se duplica un ahorro que rinde {r} % anual? (1 decimal)", "params": {"r": [3, 18, 1]}, "formula": "72/r", "tolerancia": 0.06, "unidad": "años", "pista": "Años ≈ 72 / tasa.", "explicacion": "72 / {r} = {=72/r} años aprox. (el cálculo exacto da {=Math.log(2)/Math.log(1+r/100)} años)."},
    {"tipo": "pregunta", "pregunta": "Dejas una deuda de $500.000 en la tarjeta sin pagar, al 3 % mensual, durante 12 meses. ¿Cuánto debes aproximadamente?", "opciones": ["Unos $680.000 (3 % × 12 = 36 %)", "Unos $713.000", "Unos $515.000", "Unos $1.000.000"], "respuestas": ["Unos $713.000"], "explicacion": "500.000 × 1,03¹² = **$712.880**: la deuda creció 42,6 % en un año, no 36 %, porque los intereses no pagados también generan intereses. El interés compuesto juega **en tu contra** cuando debes."},
    {"tipo": "texto", "titulo": "Valor presente: traer el futuro a hoy", "texto": "Si el dinero crece con el tiempo, entonces **un peso hoy vale más que un peso mañana**. Para comparar montos de distintas fechas hay que llevarlos al mismo momento.\n\n- **Valor futuro (VF)**: llevas un monto de hoy al futuro → **multiplicas** por (1 + r)ⁿ.\n- **Valor presente (VP)**: traes un monto futuro a hoy → **divides** por (1 + r)ⁿ. Esto se llama **descontar**.\n\nLa tasa que usas para descontar (**tasa de descuento**) es lo que podrías ganar en otra alternativa de **riesgo parecido**: tu **costo de oportunidad**.", "diagrama": "linea_vp", "porque": "Es la idea central de las finanzas: un bono, una acción, una empresa o un proyecto valen el **valor presente** de lo que van a pagar. La vas a usar en la Etapa 5 para valorar empresas."},
    {"tipo": "ejemplo", "titulo": "¿$1.000.000 hoy o $1.150.000 en 2 años?", "planteamiento": "Te ofrecen elegir. Tu alternativa (de riesgo parecido) rinde 6 % anual. ¿Qué conviene?", "pasos": [
      {"texto": "Trae los $1.150.000 a hoy, descontando 2 años al 6 %.", "calculo": "VP = VF / (1 + r)ⁿ\n1.150.000 / 1,06² = 1.150.000 / 1,1236 = $1.023.496"},
      {"texto": "Compara en la misma fecha: $1.023.496 (la oferta futura, en pesos de hoy) vs. $1.000.000 hoy."},
      {"texto": "Comprobación al revés: si tomas el millón y lo inviertes al 6 %, en 2 años tienes 1.000.000 × 1,06² = $1.123.600, menos que $1.150.000.", "calculo": "1.000.000 × 1,1236 = 1.123.600 < 1.150.000"}
    ], "resultado": "Conviene esperar: los $1.150.000 valen hoy $1.023.496 (siempre que el pago futuro sea seguro). Si tu alternativa rindiera 8 %, valdrían 1.150.000 / 1,08² = $985.940 y convendría el millón hoy."},
    {"tipo": "turno", "pregunta": "Te van a pagar ${VF} dentro de {n} años. Si tu costo de oportunidad es {r} % anual, ¿cuánto vale ese pago hoy? (redondea)", "params": {"VF": [1000000, 10000000, 250000], "n": [1, 10, 1], "r": [3, 12, 0.5]}, "formula": "VF/Math.pow(1+r/100,n)", "tolRel": 0.001, "unidad": "$", "pista": "VP = VF / (1 + r/100) elevado a n.", "explicacion": "{VF} / (1 + {r}/100)^{n} = ${=Math.round(VF/Math.pow(1+r/100,n))}."},
    {"tipo": "pregunta", "pregunta": "Si la tasa de descuento **sube**, ¿qué pasa con el valor presente de un pago futuro?", "opciones": ["Baja", "Sube", "No cambia", "Depende del monto"], "respuestas": ["Baja"], "explicacion": "Divides por un número más grande, así que el valor presente **baja**. Por eso, cuando el Banco Central sube las tasas, suelen caer los precios de los bonos y de las acciones: lo que van a pagar en el futuro vale menos hoy. Lo verás en la Etapa 3."},
    {"tipo": "texto", "titulo": "Ahorrar todos los meses: el valor futuro de los aportes", "texto": "Si aportas un monto fijo cada período, cada aporte crece por el tiempo que le queda: el primero crece casi todo el plazo y el último, nada. Sumados dan:\n\n**VF = Aporte × [(1 + r)ⁿ − 1] / r**\n\n(suponiendo el aporte al final de cada período). Regla de oro: la **tasa y los aportes en el mismo período**. Si aportas mensualmente, usa tasa **mensual** y n en **meses**.", "porque": "Así se calcula una meta de ahorro, un fondo de emergencia, el pie de una casa o la pensión de la AFP."},
    {"tipo": "ejemplo", "titulo": "$100.000 al mes durante un año", "planteamiento": "Ahorras $100.000 al final de cada mes en una cuenta que rinde 1 % mensual. ¿Cuánto tienes al mes 12?", "pasos": [
      {"texto": "Datos en el mismo período: aporte mensual, tasa mensual 0,01, n = 12 meses."},
      {"texto": "Aplica la fórmula.", "calculo": "VF = 100.000 × (1,01¹² − 1) / 0,01\n1,01¹² = 1,126825\nVF = 100.000 × 12,6825 = $1.268.250"},
      {"texto": "Aportaste 12 × $100.000 = $1.200.000; los intereses suman $68.250."}
    ], "resultado": "Tienes $1.268.250."},
    {"tipo": "turno", "pregunta": "Ahorras ${A} al final de cada mes durante {n} meses en una cuenta que rinde {r} % mensual. ¿Cuánto tienes al final? (redondea)", "params": {"A": [20000, 300000, 10000], "n": [6, 60, 6], "r": [0.2, 1.2, 0.1]}, "formula": "A*(Math.pow(1+r/100,n)-1)/(r/100)", "tolRel": 0.001, "unidad": "$", "pista": "VF = A × [(1 + r/100)ⁿ − 1] / (r/100).", "explicacion": "{A} × [(1 + {r}/100)^{n} − 1] / ({r}/100) = ${=Math.round(A*(Math.pow(1+r/100,n)-1)/(r/100))}. Aportaste ${=A*n}."},
    {"tipo": "ejemplo", "titulo": "Volvamos a Camila y Diego", "planteamiento": "Camila aporta $600.000 al año durante 10 años (25 a 35) y después deja crecer. Diego aporta $600.000 al año durante 30 años (35 a 65). Rentabilidad 7 % anual.", "pasos": [
      {"texto": "Camila a los 35 años: valor futuro de 10 aportes.", "calculo": "600.000 × (1,07¹⁰ − 1) / 0,07 = $8.289.869"},
      {"texto": "Ese monto crece 30 años más, sin aportes.", "calculo": "8.289.869 × 1,07³⁰ = 8.289.869 × 7,6123 = $63.104.595"},
      {"texto": "Diego: valor futuro de 30 aportes.", "calculo": "600.000 × (1,07³⁰ − 1) / 0,07 = $56.676.472"}
    ], "resultado": "Camila: $63,1 millones con $6 millones aportados. Diego: $56,7 millones con $18 millones aportados. Los 10 años de ventaja valen más que el triple de aportes."},
    {"tipo": "calc", "titulo": "Experimenta: aportes vs. intereses", "tarea": "Pon monto inicial **0**, aporte mensual **$50.000**, rentabilidad **7 %** y **30 años**. Mira cuánto aportaste tú y cuánto son intereses. Luego cambia a 20 años: ¿cuánto pierdes por empezar 10 años después?", "calc": "interes_compuesto"},
    {"tipo": "pregunta", "pregunta": "Con $50.000 al mes durante 30 años al 7 % anual, la calculadora da unos $58,5 millones y tú aportaste $18 millones. ¿Qué parte del total son intereses?", "opciones": ["Cerca del 69 %", "Cerca del 31 %", "Cerca del 50 %", "Cerca del 7 %"], "respuestas": ["Cerca del 69 %"], "explicacion": "Intereses = 58,5 − 18 = $40,5 millones, el **69 %** del total. A largo plazo, la mayor parte de lo que juntas lo genera el interés compuesto, no tus aportes."},
    {"tipo": "reflexion", "consigna": "Explícale a alguien de 25 años por qué Camila terminó con más plata que Diego, aunque aportó un tercio. Usa las ideas de interés compuesto y tiempo.", "modelo": "Porque con interés compuesto los intereses ganan intereses, y eso depende sobre todo del tiempo. Los aportes de Camila estuvieron invertidos entre 30 y 40 años; cada peso que puso a los 25 se multiplicó por más de 10 (1,07⁴⁰ ≈ 15). Los aportes de Diego tuvieron menos tiempo: el último casi no creció. Por eso empezar antes, aunque sea con poco, vale más que aportar mucho después. La misma lógica funciona al revés con las deudas: una deuda que no pagas crece cada vez más rápido.", "claves": ["Interés compuesto: los intereses generan intereses", "El factor clave es el tiempo, no solo la tasa", "Los primeros aportes se multiplican mucho más", "Lo mismo pasa con las deudas, en tu contra"]},
    {"tipo": "resumen", "puntos": ["El **interés** compensa esperar, la inflación y el riesgo.", "**Simple**: VF = VP × (1 + r × n). **Compuesto**: VF = VP × (1 + r)ⁿ; los intereses ganan intereses.", "**Regla del 72**: años para duplicar ≈ 72 / tasa.", "**Valor presente**: VP = VF / (1 + r)ⁿ. Se descuenta con tu **costo de oportunidad**; si la tasa sube, el VP baja.", "**Aportes periódicos**: VF = A × [(1 + r)ⁿ − 1] / r, con tasa y aportes en el **mismo período**.", "El tiempo es el ingrediente principal, a favor (ahorro) o en contra (deudas)."]}
  ],
  "caso": {
    "titulo": "Caso práctico: el tiempo y la caja de tu negocio de jugos",
    "contexto": "Tu negocio de jugos necesita una **camioneta de reparto**. Quieres juntar **$9.000.000** para el pie en **3 años (36 meses)**, en un instrumento que rinde **0,4 % mensual** (ejemplo ilustrativo, cerca de 4,9 % anual). Además, una cafetería te debe **$1.200.000** y te ofrece dos opciones: pagarte **hoy con 4 % de descuento** o pagarte **completo en 3 meses**. Cuando te falta caja usas tu línea de crédito, que cobra **1,5 % mensual**.",
    "pasos": [
      {"tipo": "predice", "pregunta": "Si ahorras $250.000 al mes durante 36 meses (9 millones aportados), ¿cuánto tendrás?", "opciones": ["Justo $9.000.000", "Algo más de $9.600.000", "Unos $10.800.000", "Menos de $9.000.000"], "respuestas": ["Algo más de $9.600.000"], "explicacion": "250.000 × (1,004³⁶ − 1) / 0,004 = **$9.659.527**. Los intereses aportan $659.527, así que puedes ahorrar menos por mes."},
      {"tipo": "pregunta", "pregunta": "¿Cuánto necesitas ahorrar al mes para llegar exactamente a $9.000.000 en 36 meses al 0,4 % mensual? (redondea al peso)", "respuesta": 232931, "tolerancia": 3, "como": "numero", "unidad": "$", "pista": "Despeja el aporte: A = VF × r / [(1 + r)ⁿ − 1].", "explicacion": "A = 9.000.000 × 0,004 / (1,004³⁶ − 1) = 36.000 / 0,15455 = **$232.931** al mes. Son $17.069 menos al mes que sin intereses."},
      {"tipo": "pregunta", "pregunta": "La cafetería: ¿cuánto recibes hoy si aceptas el 4 % de descuento?", "respuesta": 1152000, "tolerancia": 1, "como": "numero", "unidad": "$", "explicacion": "1.200.000 × 0,96 = **$1.152.000**."},
      {"tipo": "pregunta", "pregunta": "¿Cuánto valen hoy los $1.200.000 que te pagarían en 3 meses, descontados a tu costo de oportunidad de 1,5 % mensual? (redondea)", "respuesta": 1147580, "tolerancia": 3, "como": "numero", "unidad": "$", "pista": "VP = 1.200.000 / 1,015³.", "explicacion": "1.200.000 / 1,015³ = 1.200.000 / 1,04568 = **$1.147.580**."},
      {"tipo": "pregunta", "pregunta": "Entonces, ¿qué te conviene?", "opciones": ["Cobrar hoy con descuento: $1.152.000 > $1.147.580", "Esperar 3 meses: $1.200.000 es más plata", "Da exactamente lo mismo", "No se puede comparar"], "respuestas": ["Cobrar hoy con descuento: $1.152.000 > $1.147.580"], "explicacion": "Comparando en la misma fecha, el pago de hoy vale $4.420 más. Además te ahorras el riesgo de que la cafetería no pague y el uso de tu línea de crédito. Si tu costo de oportunidad fuera bajo (por ejemplo 0,4 %), convendría esperar: 1.200.000 / 1,004³ = $1.185.714."},
      {"tipo": "reflexion", "consigna": "Explica por qué '$1.200.000 en 3 meses' puede valer menos que '$1.152.000 hoy'. Menciona el valor presente y el costo de oportunidad.", "modelo": "Porque el dinero tiene un costo en el tiempo. Si hoy me falta caja, uso mi línea de crédito al 1,5 % mensual; ese es mi costo de oportunidad. Traído a valor presente con esa tasa, el pago de $1.200.000 en 3 meses vale hoy $1.147.580, menos que los $1.152.000 que me ofrecen hoy. Además, el pago de hoy no tiene riesgo de atraso o de no pago. Para comparar montos de distintas fechas, siempre hay que llevarlos a la misma fecha.", "claves": ["Comparar en la misma fecha (valor presente)", "Tasa de descuento = costo de oportunidad (la línea de crédito)", "$1.147.580 < $1.152.000", "El pago futuro además tiene riesgo"]}
    ]
  },
  "desafio": [
    {"tipo": "numero", "pregunta": "${VP} a interés SIMPLE de {r} % anual durante {n} años. ¿Valor final? (redondea)", "params": {"VP": [500000, 5000000, 100000], "r": [2, 12, 0.5], "n": [2, 10, 1]}, "formula": "VP*(1+r/100*n)", "tolRel": 0.001, "unidad": "$", "explicacion": "{VP} × (1 + {r}/100 × {n}) = ${=Math.round(VP*(1+r/100*n))}."},
    {"tipo": "numero", "pregunta": "${VP} a interés COMPUESTO de {r} % anual durante {n} años. ¿Valor final? (redondea)", "params": {"VP": [500000, 5000000, 100000], "r": [2, 12, 0.5], "n": [2, 20, 1]}, "formula": "VP*Math.pow(1+r/100,n)", "tolRel": 0.001, "unidad": "$", "explicacion": "{VP} × (1 + {r}/100)^{n} = ${=Math.round(VP*Math.pow(1+r/100,n))}."},
    {"tipo": "numero", "pregunta": "Te pagarán ${VF} en {n} años. Con un costo de oportunidad de {r} % anual, ¿cuánto vale hoy? (redondea)", "params": {"VF": [1000000, 20000000, 500000], "n": [1, 15, 1], "r": [3, 12, 0.5]}, "formula": "VF/Math.pow(1+r/100,n)", "tolRel": 0.001, "unidad": "$", "explicacion": "{VF} / (1 + {r}/100)^{n} = ${=Math.round(VF/Math.pow(1+r/100,n))}."},
    {"tipo": "numero", "pregunta": "Regla del 72: ¿en cuántos años se duplica algo que crece {r} % al año? (1 decimal)", "params": {"r": [2, 18, 1]}, "formula": "72/r", "tolerancia": 0.06, "unidad": "años", "explicacion": "72 / {r} = {=72/r} años."},
    {"tipo": "numero", "pregunta": "Regla del 72: ¿qué tasa anual necesitas para duplicar tu dinero en {n} años? (%, 1 decimal)", "params": {"n": [4, 18, 1]}, "formula": "72/n", "tolerancia": 0.06, "unidad": "%", "explicacion": "72 / {n} = {=72/n} %."},
    {"tipo": "numero", "pregunta": "Ahorras ${A} al final de cada mes durante {n} meses al {r} % mensual. ¿Cuánto juntas? (redondea)", "params": {"A": [20000, 300000, 10000], "n": [12, 120, 12], "r": [0.2, 1, 0.1]}, "formula": "A*(Math.pow(1+r/100,n)-1)/(r/100)", "tolRel": 0.001, "unidad": "$", "explicacion": "{A} × [(1 + {r}/100)^{n} − 1] / ({r}/100) = ${=Math.round(A*(Math.pow(1+r/100,n)-1)/(r/100))}."},
    {"tipo": "numero", "pregunta": "Quieres juntar ${VF} en {n} meses en una cuenta que rinde {r} % mensual. ¿Cuánto debes ahorrar al mes? (redondea)", "params": {"VF": [1000000, 12000000, 500000], "n": [12, 60, 6], "r": [0.2, 1, 0.1]}, "formula": "VF*(r/100)/(Math.pow(1+r/100,n)-1)", "tolRel": 0.002, "unidad": "$", "explicacion": "A = {VF} × ({r}/100) / [(1 + {r}/100)^{n} − 1] = ${=Math.round(VF*(r/100)/(Math.pow(1+r/100,n)-1))}."},
    {"tipo": "numero", "pregunta": "Una deuda de ${D} crece al {r} % mensual sin que pagues nada durante {n} meses. ¿Cuánto debes al final? (redondea)", "params": {"D": [200000, 2000000, 50000], "r": [1, 4, 0.5], "n": [3, 24, 1]}, "formula": "D*Math.pow(1+r/100,n)", "tolRel": 0.001, "unidad": "$", "explicacion": "{D} × (1 + {r}/100)^{n} = ${=Math.round(D*Math.pow(1+r/100,n))}."},
    {"tipo": "numero", "pregunta": "Invertiste ${VP} y en {n} años tienes ${=Math.round(VP*Math.pow(1+g/100,n))}. ¿Qué rentabilidad anual compuesta obtuviste? (%, 2 decimales)", "params": {"VP": [1000000, 5000000, 500000], "n": [2, 10, 1], "g": [2, 15, 0.5]}, "formula": "(Math.pow(Math.round(VP*Math.pow(1+g/100,n))/VP,1/n)-1)*100", "tolerancia": 0.02, "unidad": "%", "explicacion": "r = (VF / VP)^(1/{n}) − 1 = {=(Math.pow(Math.round(VP*Math.pow(1+g/100,n))/VP,1/n)-1)*100} %."},
    {"tipo": "alternativas", "pregunta": "¿Qué te conviene: ${H} hoy o $1.000.000 en 1 año, si tu alternativa de riesgo parecido rinde {r} % anual?", "params": {"H": [900000, 980000, 10000], "r": [3, 12, 1]}, "opciones": ["Comparo el VP del millón ({=Math.round(1000000/(1+r/100))}) con lo de hoy y elijo el mayor", "Siempre el millón, porque es más plata", "Siempre lo de hoy, porque es seguro", "Da lo mismo"], "respuestas": ["Comparo el VP del millón ({=Math.round(1000000/(1+r/100))}) con lo de hoy y elijo el mayor"], "explicacion": "Hay que comparar en la misma fecha: el millón vale hoy 1.000.000 / (1 + {r}/100) = ${=Math.round(1000000/(1+r/100))}, contra ${H} hoy."},
    {"tipo": "alternativas", "pregunta": "Si suben las tasas de interés del mercado, el valor presente de los pagos futuros de un bono…", "opciones": ["baja", "sube", "no cambia", "se duplica"], "respuestas": ["baja"], "explicacion": "Se divide por (1 + r)ⁿ con un r mayor."},
    {"tipo": "alternativas", "pregunta": "Aportas mensualmente y te informan una tasa anual. ¿Qué haces antes de usar la fórmula de aportes?", "opciones": ["Convierto la tasa a mensual y uso n en meses", "Uso la tasa anual con n en meses", "Divido el aporte por 12", "Nada, da lo mismo"], "respuestas": ["Convierto la tasa a mensual y uso n en meses"], "explicacion": "Tasa y aportes en el mismo período. En la clase 3 verás cómo convertir bien una tasa anual en mensual."},
    {"tipo": "alternativas", "pregunta": "¿Por qué a largo plazo el interés compuesto supera tanto al simple?", "opciones": ["Porque los intereses de cada período también generan intereses", "Porque la tasa es más alta", "Porque el banco agrega bonos", "No lo supera"], "respuestas": ["Porque los intereses de cada período también generan intereses"], "explicacion": "Interés sobre interés: el crecimiento se acelera con el tiempo."},
    {"tipo": "escritura", "pregunta": "En 60+ palabras: explica a un amigo por qué conviene empezar a ahorrar joven y por qué una deuda de tarjeta sin pagar es peligrosa.", "minPalabras": 60, "obligatorias": ["interés", "compuesto", "tiempo", "deuda"]}
  ],
  "repaso": [
    {"tipo": "numero", "etiqueta": "Valor futuro compuesto", "pregunta": "${VP} al {r} % anual compuesto por {n} años. ¿Valor final? (redondea)", "params": {"VP": [500000, 3000000, 100000], "r": [3, 10, 0.5], "n": [2, 12, 1]}, "formula": "VP*Math.pow(1+r/100,n)", "tolRel": 0.001, "unidad": "$", "explicacion": "{VP} × (1 + {r}/100)^{n} = ${=Math.round(VP*Math.pow(1+r/100,n))}."},
    {"tipo": "numero", "etiqueta": "Valor presente", "pregunta": "${VF} que recibirás en {n} años, descontados al {r} % anual. ¿Valor hoy? (redondea)", "params": {"VF": [1000000, 10000000, 500000], "n": [1, 10, 1], "r": [3, 12, 0.5]}, "formula": "VF/Math.pow(1+r/100,n)", "tolRel": 0.001, "unidad": "$", "explicacion": "{VF} / (1 + {r}/100)^{n} = ${=Math.round(VF/Math.pow(1+r/100,n))}."},
    {"tipo": "numero", "etiqueta": "Regla del 72", "pregunta": "Al {r} % anual, ¿en cuántos años se duplica? (regla del 72, 1 decimal)", "params": {"r": [3, 16, 1]}, "formula": "72/r", "tolerancia": 0.06, "unidad": "años", "explicacion": "72 / {r} = {=72/r}."},
    {"tipo": "numero", "etiqueta": "Aportes mensuales", "pregunta": "${A} al mes durante {n} meses al {r} % mensual. ¿Total? (redondea)", "params": {"A": [20000, 200000, 10000], "n": [12, 60, 12], "r": [0.2, 1, 0.1]}, "formula": "A*(Math.pow(1+r/100,n)-1)/(r/100)", "tolRel": 0.001, "unidad": "$", "explicacion": "${=Math.round(A*(Math.pow(1+r/100,n)-1)/(r/100))}."},
    {"tipo": "alternativas", "etiqueta": "Tasa de descuento", "pregunta": "La tasa con que descuentas un pago futuro debe ser…", "opciones": ["lo que ganarías en una alternativa de riesgo parecido", "siempre la inflación", "siempre 0 %", "la tasa del banco más alta que encuentres"], "respuestas": ["lo que ganarías en una alternativa de riesgo parecido"], "explicacion": "Es tu costo de oportunidad."},
    {"tipo": "alternativas", "etiqueta": "Tasa sube → VP", "pregunta": "Si sube la tasa de descuento, el valor presente…", "opciones": ["baja", "sube", "no cambia", "depende del plazo"], "respuestas": ["baja"], "explicacion": "Divides por un número mayor."},
    {"tipo": "alternativas", "etiqueta": "Deuda compuesta", "pregunta": "Una deuda al 3 % mensual sin pagar durante 12 meses crece…", "opciones": ["cerca de 43 %", "36 %", "3 %", "12 %"], "respuestas": ["cerca de 43 %"], "explicacion": "1,03¹² − 1 = 42,6 %."},
    {"tipo": "alternativas", "etiqueta": "Camila vs. Diego", "pregunta": "Aportar 10 años desde los 25 vs. aportar 30 años desde los 35 (misma cuota, 7 %). ¿Quién junta más a los 65?", "opciones": ["El que empezó a los 25", "El que aportó 30 años", "Igual", "Depende de la inflación"], "respuestas": ["El que empezó a los 25"], "explicacion": "Sus aportes tienen más tiempo para componer: $63,1 M vs. $56,7 M."},
    {"tipo": "numero", "etiqueta": "Comparar fechas", "pregunta": "Hoy te ofrecen ${H} o $1.200.000 en 3 meses. Tu costo de oportunidad es {r} % mensual. ¿Cuánto vale hoy el pago futuro? (redondea)", "params": {"H": [1100000, 1180000, 10000], "r": [0.5, 2, 0.5]}, "formula": "1200000/Math.pow(1+r/100,3)", "tolRel": 0.001, "unidad": "$", "explicacion": "1.200.000 / (1 + {r}/100)³ = ${=Math.round(1200000/Math.pow(1+r/100,3))}; compáralo con ${H}."},
    {"tipo": "alternativas", "etiqueta": "Simple vs. compuesto", "pregunta": "$1.000.000 al 6 % por 3 años: simple da $1.180.000. ¿Compuesto?", "opciones": ["$1.191.016", "$1.180.000", "$1.060.000", "$1.218.000"], "respuestas": ["$1.191.016"], "explicacion": "1.000.000 × 1,06³."}
  ],
  "ficha": {
    "ideas": ["El **interés** paga esperar + inflación + riesgo.", "**Compuesto**: los intereses ganan intereses; el ingrediente clave es el **tiempo**.", "**Valor presente**: un peso hoy vale más que un peso mañana; para comparar fechas, lleva todo a hoy.", "La **tasa de descuento** es tu **costo de oportunidad** (alternativa de riesgo parecido).", "Tasa y aportes en el **mismo período**.", "El compuesto también juega **en contra** en las deudas."],
    "formulas": ["Simple: VF = VP × (1 + r × n)", "Compuesto: VF = VP × (1 + r)ⁿ", "Valor presente: VP = VF / (1 + r)ⁿ", "Regla del 72: años para duplicar ≈ 72 / tasa (%)", "Aportes: VF = A × [(1 + r)ⁿ − 1] / r", "Aporte para una meta: A = VF × r / [(1 + r)ⁿ − 1]", "Rentabilidad compuesta: r = (VF / VP)^(1/n) − 1"]
  },
  "accion": "Elige una meta concreta (fondo de emergencia, pie, equipo para tu negocio). Define el monto y el plazo, y calcula con la fórmula del aporte cuánto tendrías que ahorrar al mes. Después revisa si tienes deudas con interés (tarjeta, línea de crédito) y calcula cuánto crecerían en 12 meses si no las pagas.",
  "calculadoras": ["interes_compuesto"],
  "terminos": [
    {"es": "interés compuesto", "en": "compound interest", "definicion": "Intereses que se suman al capital y generan nuevos intereses.", "ejemplo": "Compound interest makes money grow faster over time."},
    {"es": "valor presente", "en": "present value (PV)", "definicion": "Valor hoy de un monto futuro, descontado a una tasa.", "ejemplo": "The present value of $1,150,000 in two years is $1,023,496."},
    {"es": "valor futuro", "en": "future value (FV)", "definicion": "Valor que alcanza hoy un monto al invertirlo a una tasa por un plazo.", "ejemplo": "The future value grows with time."},
    {"es": "tasa de descuento", "en": "discount rate", "definicion": "Tasa usada para traer montos futuros a hoy; refleja el costo de oportunidad.", "ejemplo": "A higher discount rate lowers the present value."},
    {"es": "costo de oportunidad", "en": "opportunity cost", "definicion": "Lo que dejas de ganar en la mejor alternativa que no elegiste.", "ejemplo": "My opportunity cost is my credit line rate."},
    {"es": "anualidad", "en": "annuity", "definicion": "Serie de pagos o aportes iguales y periódicos.", "ejemplo": "Monthly savings form an annuity."},
    {"es": "regla del 72", "en": "rule of 72", "definicion": "Atajo: años para duplicar ≈ 72 / tasa.", "ejemplo": "At 8%, the rule of 72 says money doubles in about 9 years."}
  ],
  "fuentes": [
    {"titulo": "CMF Educa — Interés compuesto", "url": "https://www.cmfchile.cl/educa/621/w3-propertyvalue-1208.html"},
    {"titulo": "CMF Educa — ¿En qué consiste la tasa de interés?", "url": "https://www.cmfchile.cl/educa/621/w3-article-27169.html"},
    {"titulo": "CMF Educa — ¿Qué es el ahorro?", "url": "https://www.cmfchile.cl/educa/621/w3-article-27547.html"},
    {"titulo": "Investor.gov (SEC) — Compound Interest Calculator", "url": "https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator"}
  ]
}
);
