window.CLASES_RIC = window.CLASES_RIC || []; window.CLASES_RIC.push(
{
  "id": 201,
  "etapa": 1,
  "formato": "leccion",
  "titulo": "La instalación de principio a fin y quién la regula",
  "subtitulo": "Qué cubre la norma, para qué existe, quién responde y cómo se llega a tener luz",
  "objetivo": "Ver el mapa completo antes de los detalles: el recorrido de la energía, los dos peligros que la norma combate, quién hace qué (propietario, instalador, SEC, distribuidora) y el trámite para energizar.",
  "gancho": "Un cliente compró un sitio en Rancagua y va a construir su casa. Te pregunta: **¿quién puede hacer la instalación, qué trámites hay que hacer, en cuánto tiempo tendré luz y quién responde si mañana hay un incendio?** Al terminar esta lección vas a poder responderle con el artículo exacto, y vas a saber para qué sirve cada uno de los 19 pliegos RIC.",
  "leccion": [
    {"tipo": "predice", "pregunta": "Antes de empezar: ¿desde dónde hasta dónde rige el reglamento de instalaciones de consumo (DS 8 y pliegos RIC)?", "opciones": ["Desde la central eléctrica hasta el enchufe", "Desde el punto de conexión con la red de distribución hacia adentro de la propiedad", "Solo el tablero y los enchufes", "Solo edificios grandes y comerciales"], "respuestas": ["Desde el punto de conexión con la red de distribución hacia adentro de la propiedad"], "explicacion": "El DS 8 regula la instalación de consumo 'hasta el punto de conexión del cliente final con la red de distribución'. Lo que está del lado de la red (postes, transformadores) es de la distribuidora y tiene otras normas."},
    {"tipo": "texto", "titulo": "El recorrido de la energía", "texto": "Una **instalación de consumo** es el conjunto de aparatos, equipos, canalizaciones y circuitos que tienen como objetivo **usar** la energía eléctrica (DS 8, art. 4° c).\n\nLa energía hace este camino:\n- **Red de distribución** (de la distribuidora) → llega al **punto de conexión**.\n- **Empalme y medidor**: la conexión con la red y la medición (RIC N°01).\n- **Alimentador**: los conductores del medidor al primer tablero (RIC N°03 y N°04).\n- **Tableros**: protegen y permiten maniobrar los circuitos (RIC N°02).\n- **Circuitos y puntos**: enchufes, luminarias y equipos (RIC N°04, N°10, N°07).\n\nY en toda la instalación: **protección de las personas** (RIC N°05) y **puesta a tierra** (RIC N°06).", "diagrama": "recorrido_energia", "porque": "El curso sigue este mismo recorrido, como un proyecto real: primero llevas la energía a la casa (empalme, tablero), después dimensionas (conductores, canalizaciones), proteges a las personas y al final presentas y declaras el proyecto."},
    {"tipo": "norma", "titulo": "El objetivo de todo el reglamento", "ref": "DS N°8/2019 · Artículo 1°", "cita": "El presente reglamento establece las exigencias mínimas que deben ser consideradas en el diseño, construcción, puesta en servicio, operación, reparación y mantenimiento de toda instalación de consumo de energía eléctrica hasta el punto de conexión del cliente final con la red de distribución, para que su funcionamiento sea en condiciones seguras para las personas y las cosas.", "simple": "La norma cubre **todo el ciclo de vida** de la instalación (diseñar, construir, poner en servicio, operar, reparar, mantener) y tiene **un solo objetivo: la seguridad de las personas y de las cosas**. Son exigencias **mínimas**: puedes hacerlo mejor, nunca peor.", "porque": "Cuando una exigencia te parezca rara, pregúntate: ¿qué accidente evita? Siempre hay una respuesta, y entenderla te permite aplicar la norma en casos que el pliego no describe literalmente."},
    {"tipo": "texto", "titulo": "Los dos peligros que la norma combate", "texto": "Casi cada exigencia de los 19 pliegos existe para evitar uno de estos dos peligros:\n\n**1. Incendio.** Un conductor que lleva más corriente de la que soporta se calienta (**sobrecarga**); una falla entre conductores produce una corriente enorme en milisegundos (**cortocircuito**); una conexión floja genera un punto caliente.\n\n**2. Choque eléctrico.** Tocar algo energizado: una parte activa, como un borne o un cable pelado (**contacto directo**), o una carcasa metálica que quedó energizada por una falla de aislación (**contacto indirecto**).", "diagrama": "riesgos", "porque": "Si entiendes el peligro, deduces la regla: el termomagnético protege al CONDUCTOR (incendio); el diferencial y la puesta a tierra protegen a la PERSONA (choque)."},
    {"tipo": "pregunta", "pregunta": "Una lavadora tiene una falla de aislación y su carcasa metálica quedó energizada. Alguien la toca. ¿Qué tipo de contacto es y qué protege a esa persona?", "opciones": ["Contacto indirecto: el diferencial y la puesta a tierra", "Contacto directo: el termomagnético", "Sobrecarga: un conductor más grueso", "Cortocircuito: el fusible del empalme"], "respuestas": ["Contacto indirecto: el diferencial y la puesta a tierra"], "pista": "La persona no tocó una parte activa, sino una carcasa que normalmente no tiene tensión.", "explicacion": "Es **contacto indirecto**: la carcasa no debería tener tensión, la adquirió por una falla. La **puesta a tierra** da un camino a la corriente de falla y el **diferencial** detecta la fuga y corta en milisegundos. El termomagnético no sirve aquí: una corriente de 30 mA puede ser mortal y está muy lejos de hacerlo operar."},
    {"tipo": "pregunta", "pregunta": "En un enchufe múltiple conectan estufa, hervidor y secador de pelo. Nada falla, pero el cable se calienta. ¿Qué fenómeno es y qué protección debería actuar?", "opciones": ["Sobrecarga: la parte térmica del termomagnético", "Cortocircuito: el diferencial", "Contacto indirecto: la puesta a tierra", "Ninguno: es normal que se caliente"], "respuestas": ["Sobrecarga: la parte térmica del termomagnético"], "explicacion": "La suma de las potencias exige más corriente de la que el circuito soporta: es una **sobrecarga**. La parte **térmica** del termomagnético la detecta (actúa más lento cuanto menor es el exceso). El diferencial no la ve, porque no hay fuga a tierra: toda la corriente que va, vuelve."},
    {"tipo": "texto", "titulo": "Quién manda: la pirámide normativa", "texto": "- **Ley General de Servicios Eléctricos** (DFL N°4/20.018 de 2006): el marco.\n- **DS N°8/2019** del Ministerio de Energía: el reglamento. Dice **qué** se exige en general y **quién responde**. Rige desde el **12 de julio de 2021**, junto con los pliegos, y reemplazó a la antigua **NCh Elec. 4/2003**.\n- **19 Pliegos Técnicos Normativos RIC**, dictados por la **SEC** (Superintendencia de Electricidad y Combustibles): dicen **cómo**, punto por punto. El RIC N°15 (recarga de vehículos eléctricos) tiene una versión de 2024.\n- **Normas IEC/UNE**: se aplican solo donde un pliego las cita.\n\nAparte, el **DS N°92/1983** regula las **licencias** de los instaladores eléctricos.", "diagrama": "piramide_normativa", "porque": "Cuando la SEC observa una instalación, cita el punto exacto: por ejemplo, 'RIC N°01, 7.2'. Hablar ese idioma es lo que distingue a un instalador profesional."},
    {"tipo": "pregunta", "pregunta": "¿Quién dicta los pliegos RIC y quién fiscaliza que se cumplan?", "opciones": ["La SEC dicta los pliegos y también fiscaliza", "El Ministerio de Energía dicta los pliegos y la distribuidora fiscaliza", "La distribuidora dicta los pliegos y la SEC fiscaliza", "El INN dicta los pliegos y el municipio fiscaliza"], "respuestas": ["La SEC dicta los pliegos y también fiscaliza"], "explicacion": "El DS 8 encarga a la SEC dictar los pliegos de normas técnicas (art. 12°) y la designa como el organismo que fiscaliza y supervigila su cumplimiento (art. 20°). El Ministerio de Energía dictó el reglamento (DS 8)."},
    {"tipo": "texto", "titulo": "Cómo se lee un pliego", "texto": "Todos los pliegos tienen la misma estructura:\n- **1. Objetivo** y **2. Alcance**: qué instalaciones cubre.\n- **3. Referencias normativas**: las normas IEC/UNE que cita.\n- **4. Terminología**: las definiciones. Léelas, porque una palabra puede significar algo muy preciso.\n- **5 en adelante: exigencias** numeradas jerárquicamente: **7.2** es el punto 2 del capítulo 7; **6.1.21.2** es un sub-subpunto.\n- **Anexos**: tablas y figuras (por ejemplo, el **anexo 1.1** muestra dónde ubicar el medidor).\n\nUna exigencia se cita así: **RIC N°01, punto 7.2**.", "porque": "No vas a memorizar 551 páginas: vas a saber **dónde buscar**. Un buen instalador sabe en qué pliego y capítulo está cada tema."},
    {"tipo": "norma", "titulo": "Quién responde por la instalación", "ref": "DS N°8/2019 · Artículo 6°", "cita": "Los Propietarios de Instalaciones de Consumo de Energía Eléctrica serán responsables de mantener y conservar sus instalaciones en buen estado y con una operación segura, siendo responsables de las normalizaciones y regularizaciones de ellas. Las personas que diseñen, construyan y/o modifiquen Instalaciones de Consumo de Energía Eléctrica serán responsables del cumplimiento de la normativa vigente, con el objetivo de que dichas instalaciones sean seguras para las personas y las cosas.", "simple": "Hay **dos responsables**:\n- El **propietario** responde por **mantener** la instalación segura y por regularizarla. Si no cumple, la SEC puede **multarlo y/o desconectar** (art. 5°).\n- Quien **diseña, construye o modifica** (el instalador) responde porque lo que hizo **cumpla la norma**.\n\nAdemás, el propietario debe guardar copia de las declaraciones y del plano definitivo (art. 13°).", "porque": "Si un cliente te pide 'hazlo más barato, sin diferencial', tú respondes por lo que construiste. Y el cliente sigue respondiendo por mantenerlo."},
    {"tipo": "norma", "titulo": "Con proyecto y con instalador autorizado", "ref": "DS N°8/2019 · Artículos 7° y 8°", "cita": "Toda Instalación de Consumo de Energía Eléctrica deberá ejecutarse de acuerdo a un proyecto técnicamente elaborado […]. Toda Instalación de Consumo de Energía Eléctrica debe ser proyectada, ejecutada y dirigida por un instalador eléctrico autorizado por la Superintendencia, o bien, por los que posean título en las profesiones que determinen los reglamentos, y de la clase correspondiente según lo establecido en el decreto supremo N° 92, de 1983 […].", "simple": "**Nada se hace 'a ojo'**: primero hay un **proyecto** (planos y cálculos) y lo ejecuta y dirige un **instalador autorizado por la SEC** cuya **clase de licencia** alcance para esa instalación.", "porque": "El proyecto obliga a calcular antes de construir: corriente, sección del conductor, caída de tensión, protecciones. La mayoría de los incendios eléctricos vienen de instalaciones 'improvisadas'."},
    {"tipo": "texto", "titulo": "Las licencias: qué puede hacer cada clase (DS 92/1983)", "texto": "- **Clase A**: alta y baja tensión, **sin límite** de potencia.\n- **Clase B**: baja tensión **hasta 500 kW**, incluidas instalaciones con **riesgo de explosión o incendio** y recintos de **espectáculos públicos**.\n- **Clase C**: baja tensión; **alumbrado hasta 100 kW** y **fuerza motriz/calefacción hasta 50 kW**, con alimentadores de máximo **10 kW por fase y 100 m** de largo.\n- **Clase D**: baja tensión **sin alimentadores**; **alumbrado hasta 10 kW** y **fuerza/calefacción hasta 5 kW**.\n\nCada límite se cumple por separado: basta que **una** condición se pase para necesitar la clase siguiente.", "porque": "Firmar una instalación que excede tu licencia la deja irregular y te expone a sanciones (DS 8, art. 9° y 21°)."},
    {"tipo": "ejemplo", "titulo": "¿Qué licencia necesita este taller?", "planteamiento": "Un taller mecánico: alumbrado **30 kW**, fuerza motriz **40 kW**, alimentadores de **8 kW por fase** y **60 m**. En baja tensión, sin riesgo de explosión.", "pasos": [
      {"texto": "¿Clase D? Exige **sin alimentadores**, alumbrado ≤ 10 kW y fuerza ≤ 5 kW. El taller tiene alimentadores, 30 kW de alumbrado y 40 kW de fuerza: **no**."},
      {"texto": "¿Clase C? Revisa cada límite.", "calculo": "Alumbrado 30 kW ≤ 100 kW ✓\nFuerza 40 kW ≤ 50 kW ✓\nAlimentadores 8 kW/fase ≤ 10 kW ✓ y 60 m ≤ 100 m ✓"},
      {"texto": "Todo cumple, así que basta la **clase C**. Si mañana la fuerza sube a **60 kW**, se pasa de 50 kW y necesitarías **clase B**."}
    ], "resultado": "Licencia mínima: clase C (también puede hacerlo un B o un A)."},
    {"tipo": "pregunta", "pregunta": "Una bencinera de 120 kW en baja tensión (hay riesgo de explosión). ¿Licencia mínima?", "opciones": ["Clase B", "Clase C", "Clase D", "Cualquier clase, si la potencia es baja"], "respuestas": ["Clase B"], "pista": "Mira qué clase menciona expresamente el riesgo de explosión.", "explicacion": "La **clase B** incluye expresamente las instalaciones con riesgo de explosión o incendio (hasta 500 kW en BT). La C no las cubre, aunque la potencia esté dentro de sus límites."},
    {"tipo": "pregunta", "pregunta": "Un local comercial: alumbrado 15 kW, fuerza 3 kW, alimentador de 6 kW por fase y 40 m. ¿Licencia mínima?", "opciones": ["Clase C", "Clase D", "Clase B", "Clase A"], "respuestas": ["Clase C"], "explicacion": "No puede ser **D**: el alumbrado (15 kW) supera 10 kW y además tiene alimentador. La **C** cubre todo: alumbrado ≤ 100 kW, fuerza ≤ 50 kW, alimentador ≤ 10 kW por fase y ≤ 100 m."},
    {"tipo": "norma", "titulo": "Las modificaciones también se declaran", "ref": "DS N°8/2019 · Artículos 16° y 18°", "cita": "Todas las Instalaciones de Consumo de Energía Eléctrica, las modificaciones de éstas y las instalaciones provisorias, deberán ser declaradas por el instalador eléctrico autorizado […] a la Superintendencia para su puesta en servicio […]. Se entenderá por modificación […] todo cambio en el diseño o topología de la instalación, como, entre otros, los siguientes: a) Aumento de capacidad de la instalación […]", "simple": "Se declaran a la SEC las instalaciones **nuevas**, las **modificaciones** y las **provisorias**. Es modificación todo cambio de diseño o topología; por ejemplo: **aumentar la capacidad**, cambiar circuitos en zonas de seguridad, cualquier cambio en **media tensión**, en **ambientes explosivos** o en consumos que **no toleran interrupciones**.", "porque": "Muchos incendios ocurren en casas 'ampliadas' donde se agregaron cargas sin recalcular. Por eso una ampliación no es 'un arreglito': es una modificación que se proyecta y se declara."},
    {"tipo": "pregunta", "pregunta": "Un cliente quiere agregar un circuito para un horno eléctrico y un cargador de auto, lo que aumenta la capacidad de su instalación. ¿Hay que declararlo a la SEC?", "opciones": ["Sí: es una modificación (aumento de capacidad) y se declara", "No: solo se declaran las instalaciones nuevas", "Solo si el cliente lo pide", "No, si lo hace un instalador clase A"], "respuestas": ["Sí: es una modificación (aumento de capacidad) y se declara"], "explicacion": "El aumento de capacidad es una **modificación** (art. 18° a) y todas las modificaciones se declaran (art. 16°). Además, el cargador de vehículos tiene su propio pliego, el RIC N°15."},
    {"tipo": "texto", "titulo": "El camino para tener luz: el trámite completo", "texto": "Siete pasos, en este orden (míralos en el diagrama). Los detalles que más se preguntan:\n- La **factibilidad** se pide **antes** de proyectar (RIC N°19, 9.2.1): la distribuidora dice si puede dar el suministro y en qué condiciones.\n- La **declaración** la ingresa el **instalador** en el sistema **e-declarador**, con su clave (9.1.2 y 9.1.3). Lleva los **planos as-built**, la memoria, el **informe de verificación inicial** y los certificados de tercera parte que correspondan (9.2.8).\n- Se declara con **15 días hábiles de anticipación** a la puesta en servicio (art. 17° y RIC N°19, 9.1.1).\n- La SEC **inscribe** la declaración y entrega un documento para **pedir el suministro** (9.2.11). La distribuidora **no puede conectar** una instalación que no fue comunicada (art. 18°).\n- Desde la energización, la responsabilidad de mantenerla es del **propietario** (art. 10°).", "diagrama": "tramite_linea", "porque": "Con este mapa le puedes explicar a tu cliente cuánto se demora el proceso y por qué no puede 'conectarse no más'."},
    {"tipo": "pregunta", "pregunta": "Los plazos del DS 8 son en **días hábiles**: no cuentan sábados, domingos ni festivos (art. 22°). Quieres poner en servicio una instalación un **lunes** y no hay feriados en medio. Si necesitas 15 días hábiles de anticipación, ¿cuántos **días corridos** antes debes declarar, como mínimo?", "respuesta": 21, "tolerancia": 0, "como": "numero", "unidad": "días", "pista": "Una semana tiene 5 días hábiles. ¿Cuántas semanas son 15 días hábiles?", "explicacion": "15 días hábiles = 3 semanas de lunes a viernes. Contando hacia atrás desde el lunes, el día hábil 15 es el lunes de tres semanas antes: **21 días corridos**. Si hay feriados en medio, son más. Error típico: pensar que '15 días' son dos semanas."},
    {"tipo": "pregunta", "pregunta": "La SEC devolvió tu declaración con observaciones. ¿Qué haces?", "opciones": ["Corrijo las observaciones y sigo con la MISMA declaración", "Ingreso una declaración nueva para reemplazarla", "Ingreso dos declaraciones para que una pase más rápido", "Le pido a la distribuidora que conecte igual"], "respuestas": ["Corrijo las observaciones y sigo con la MISMA declaración"], "explicacion": "El RIC N°19 (9.2.10) obliga a continuar con la misma declaración, corrigiendo hasta completar la inscripción, y **prohíbe** presentar una nueva para reemplazar la devuelta. Tampoco se permiten ingresos simultáneos de la misma instalación (9.2.9)."},
    {"tipo": "norma", "titulo": "Un primer punto técnico: dónde va el medidor", "ref": "RIC N°01 · 7.2 y 7.3 (anexo 1.1)", "cita": "Para construcciones habitacionales unifamiliares u otro tipo de recintos, conectados a través de un empalme único, la unidad de medida de éste deberá ubicarse en la fachada principal de la vivienda, con vista frontal desde la vía pública de acceso, permitiendo una fácil lectura desde el exterior de la propiedad e impidiéndose su manipulación por terceros, y dentro de un semicírculo de radio no superior a 15 m, con centro en la puerta de acceso desde la vía pública al punto de medición.", "simple": "El medidor de una casa va en la **fachada principal**, **visible desde la calle** y **a 15 m como máximo** de la puerta de acceso desde la vía pública. Si la casa queda más lejos, se instala **cerca de la línea de cierre**, en una estructura exclusiva para eso, como un poste o un nicho (7.3).", "diagrama": "semicirculo_15m", "porque": "La distribuidora tiene que poder leer, revisar y cortar el medidor **sin entrar** a la propiedad, y nadie debe poder manipularlo. Esta regla la vas a profundizar en la clase de Empalmes."},
    {"tipo": "pregunta", "pregunta": "La casa de tu cliente está a 25 m de la puerta de acceso desde la calle. ¿Dónde va el medidor?", "opciones": ["Cerca de la línea de cierre, en una estructura exclusiva (poste o nicho)", "En la fachada de la casa, igual", "Dentro de la casa, junto al tablero", "Donde el cliente prefiera"], "respuestas": ["Cerca de la línea de cierre, en una estructura exclusiva (poste o nicho)"], "explicacion": "A 25 m, la fachada queda fuera del semicírculo de 15 m. Según el RIC N°01 7.3, el medidor va en un punto próximo a la línea de cierre, en una estructura construida o instalada **exclusivamente** para eso."},
    {"tipo": "reflexion", "consigna": "Tu cliente te pregunta: 'Si la instalación la haces tú, ¿por qué yo tengo que responder si después hay un problema?'. Explícale quién responde por qué, con los artículos del DS 8.", "modelo": "Hay dos responsabilidades distintas. Yo, como instalador autorizado, respondo porque lo que diseño y construyo cumpla la norma (art. 6°): hago un proyecto (art. 7°), lo ejecuto con mi licencia (art. 8°) y lo declaro a la SEC (art. 16°). Pero una vez energizada la instalación, tú como propietario respondes por mantenerla en buen estado y operando en forma segura (arts. 6° y 10°). Si después alguien agrega cargas o cambia circuitos sin declararlo, eso es una modificación irregular (arts. 16° y 18°), y la SEC puede multar o desconectar (art. 5° y 9°).", "claves": ["Instalador: responde por cumplir la norma en lo que diseña, construye o modifica (art. 6°)", "Propietario: responde por mantener la instalación segura después de energizada (arts. 6° y 10°)", "Las modificaciones también se proyectan y declaran (arts. 16° y 18°)", "La SEC puede multar y/o desconectar (arts. 5° y 9°)"]},
    {"tipo": "resumen", "puntos": ["La norma rige desde el **punto de conexión** con la red hacia adentro, durante todo el ciclo de vida de la instalación (DS 8, art. 1°).", "Su único objetivo es la **seguridad**: evitar **incendio** (sobrecarga, cortocircuito, malas conexiones) y **choque eléctrico** (contacto directo e indirecto).", "Pirámide: **Ley → DS 8 (qué y quién) → 19 pliegos RIC de la SEC (cómo) → normas IEC citadas**. Las licencias están en el **DS 92**.", "**Propietario**: mantener la instalación segura. **Instalador**: cumplir la norma en lo que hace. **SEC**: dicta los pliegos y fiscaliza.", "Licencias: **A** sin límite · **B** ≤ 500 kW (incluye explosivos y espectáculos) · **C** alumbrado ≤ 100 kW, fuerza ≤ 50 kW, alimentadores ≤ 10 kW/fase y 100 m · **D** alumbrado ≤ 10 kW, fuerza ≤ 5 kW, sin alimentadores.", "Trámite: factibilidad → proyecto → ejecución → verificación → declaración en e-declarador (**15 días hábiles** antes) → inscripción → conexión → mantención."]}
  ],
  "caso": {
    "titulo": "Caso práctico: la casa nueva en Rancagua",
    "contexto": "Tu cliente construye una casa de un piso en un sitio de 12 × 40 m. La casa queda **retirada 12 m** de la reja, y la puerta de acceso está en la reja. Tendrá alumbrado por **2 kW** y enchufes y equipos por **6 kW** (incluye horno y termo eléctrico), con un **tablero junto al medidor**. En el patio, un **taller de soldadura**: **9 kW** de fuerza con un **alimentador de 8 kW por fase y 30 m** desde el tablero principal. Pide **empalme monofásico de 220 V**.",
    "pasos": [
      {"tipo": "predice", "pregunta": "¿Qué es lo PRIMERO que hay que hacer?", "opciones": ["Pedir a la distribuidora la factibilidad técnica de suministro", "Comprar los materiales", "Declarar la instalación a la SEC", "Pedir que conecten un empalme provisorio"], "respuestas": ["Pedir a la distribuidora la factibilidad técnica de suministro"], "explicacion": "Antes de proyectar se pide la factibilidad técnica (DS 8 art. 15°; RIC N°19 9.2.1): la distribuidora informa si puede dar el suministro y en qué condiciones. Por ejemplo, puede que no tenga capacidad en ese transformador."},
      {"tipo": "pregunta", "pregunta": "¿Qué licencia mínima necesitas para firmar esta instalación (casa + taller)?", "opciones": ["Clase C", "Clase D", "Clase B", "Clase A"], "respuestas": ["Clase C"], "pista": "La fuerza total es 6 + 9 = 15 kW y hay un alimentador hacia el taller.", "explicacion": "La **D** no sirve: hay un alimentador al taller y la fuerza total (6 + 9 = 15 kW) supera 5 kW. La **C** cubre todo: alumbrado 2 kW ≤ 100, fuerza 15 kW ≤ 50, alimentador 8 kW/fase ≤ 10 y 30 m ≤ 100."},
      {"tipo": "pregunta", "pregunta": "¿Dónde va el medidor?", "opciones": ["En la fachada principal de la casa, visible desde la calle", "Obligatoriamente en un poste en la reja", "Dentro de la casa", "En el taller"], "respuestas": ["En la fachada principal de la casa, visible desde la calle"], "explicacion": "La fachada está a 12 m de la puerta de acceso: queda **dentro** del semicírculo de 15 m (RIC N°01, 7.2). Va en la fachada principal, con vista frontal desde la calle y sin que terceros puedan manipularlo. Si estuviera a más de 15 m, iría cerca de la reja (7.3)."},
      {"tipo": "pregunta", "pregunta": "Un adelanto de la próxima clase: en monofásico, la potencia que puede entregar el empalme es **P = V × I**. Si la protección del empalme es de **40 A** a **220 V**, ¿cuántos kVA puede entregar como máximo?", "respuesta": 8.8, "tolerancia": 0.05, "como": "numero", "unidad": "kVA", "pista": "220 × 40 = ? VA. Divide por 1.000 para pasar a kVA.", "explicacion": "220 V × 40 A = 8.800 VA = **8,8 kVA**. Con alumbrado y enchufes que pueden sumar más que eso al mismo tiempo, más el taller, quizás haya que estudiar un empalme mayor o trifásico. Eso se calcula con la **demanda** (RIC N°03) y la tabla del RIC N°01: lo verás en las próximas clases."},
      {"tipo": "pregunta", "pregunta": "Quieres energizar el lunes 9 de noviembre y no hay feriados entre medio. ¿Cuál es el último día en que puedes ingresar la declaración (15 días hábiles antes)?", "opciones": ["Lunes 19 de octubre", "Lunes 26 de octubre", "Sábado 24 de octubre", "Viernes 30 de octubre"], "respuestas": ["Lunes 19 de octubre"], "explicacion": "Contando hacia atrás desde el lunes 9: 15 días hábiles son tres semanas de lunes a viernes, así que el último día es el **lunes 19 de octubre** (21 días corridos antes)."},
      {"tipo": "pregunta", "pregunta": "Dos años después, el dueño agrega por su cuenta un cargador de auto y un aire acondicionado, sin proyecto ni declaración. Se produce un principio de incendio. ¿Quién responde?", "opciones": ["El propietario, por la modificación irregular y por no mantener la instalación segura; y quien hizo la modificación, por no cumplir la norma", "Solo tú, porque firmaste la instalación original", "Solo la distribuidora", "Nadie, porque era una casa particular"], "respuestas": ["El propietario, por la modificación irregular y por no mantener la instalación segura; y quien hizo la modificación, por no cumplir la norma"], "explicacion": "Tras la energización, el propietario responde por mantenerla segura (art. 10°). Aumentar la capacidad es una **modificación** que debía proyectarse y declararse (arts. 16° y 18°), y quien la ejecutó responde por cumplir la norma (art. 6°). Tú respondes por lo que tú hiciste, y por eso conviene guardar el proyecto y la declaración (art. 13°)."},
      {"tipo": "reflexion", "consigna": "Escríbele al cliente un plan breve: qué pasos siguen, en qué orden, quién hace cada uno y cuánto tiempo mínimo hay entre la declaración y la conexión.", "modelo": "1) Pedimos a la distribuidora la factibilidad técnica de suministro. 2) Con esa respuesta hago el proyecto (planos y cálculos: demanda, conductores, protecciones, empalme). 3) Ejecuto la instalación con mi licencia clase C. 4) Hago las pruebas y la verificación inicial. 5) Declaro la instalación a la SEC en el e-declarador con los planos as-built y el informe, al menos 15 días hábiles antes de energizar. 6) Con el documento de inscripción de la SEC pedimos la conexión a la distribuidora. 7) Desde ahí, usted es responsable de mantenerla segura, y cualquier ampliación hay que proyectarla y declararla.", "claves": ["Factibilidad primero", "Proyecto → ejecución → pruebas → declaración", "15 días hábiles de anticipación", "Inscripción SEC antes de que la distribuidora conecte", "Después: mantención y modificaciones declaradas"]}
    ]
  },
  "desafio": [
    {"tipo": "alternativas", "pregunta": "¿Hasta dónde rige el DS 8 hacia la red?", "opciones": ["Hasta el punto de conexión del cliente final con la red de distribución", "Hasta el transformador de la distribuidora", "Hasta la subestación más cercana", "Solo hasta el tablero"], "respuestas": ["Hasta el punto de conexión del cliente final con la red de distribución"], "explicacion": "DS 8, art. 1°."},
    {"tipo": "alternativas", "pregunta": "Una persona toca un borne energizado dentro de un tablero abierto. ¿Qué tipo de contacto es?", "opciones": ["Contacto directo", "Contacto indirecto", "Sobrecarga", "Cortocircuito"], "respuestas": ["Contacto directo"], "explicacion": "Tocar una parte activa es contacto directo. Se previene con aislación, envolventes y tapas; el diferencial es la protección complementaria."},
    {"tipo": "alternativas", "pregunta": "¿Qué protege principalmente al CONDUCTOR contra sobrecargas y cortocircuitos?", "opciones": ["El interruptor termomagnético", "El diferencial", "La puesta a tierra", "El medidor"], "respuestas": ["El interruptor termomagnético"], "explicacion": "El termomagnético protege al conductor (riesgo de incendio). El diferencial y la tierra protegen a las personas."},
    {"tipo": "alternativas", "pregunta": "¿Qué norma dejó de regir con la entrada en vigencia del DS 8 y los pliegos RIC (12-07-2021)?", "opciones": ["NCh Elec. 4/2003", "DS 92/1983", "Ley General de Servicios Eléctricos", "Ley 18.410"], "respuestas": ["NCh Elec. 4/2003"], "explicacion": "El DS 92 (licencias) sigue vigente."},
    {"tipo": "alternativas", "pregunta": "¿Qué dice el DS 8 que el reglamento no detalla y qué dicen los pliegos?", "opciones": ["El DS 8 dice qué se exige y quién responde; los pliegos dicen cómo, punto por punto", "El DS 8 tiene las tablas técnicas y los pliegos las sanciones", "Son lo mismo con distinto nombre", "Los pliegos son recomendaciones, no obligatorios"], "respuestas": ["El DS 8 dice qué se exige y quién responde; los pliegos dicen cómo, punto por punto"], "explicacion": "Los pliegos son obligatorios: los dicta la SEC por encargo del DS 8 (art. 12°)."},
    {"tipo": "alternativas", "pregunta": "Instalación de fuerza motriz de 4 kW y alumbrado de 3 kW, sin alimentadores. ¿Licencia mínima?", "opciones": ["Clase D", "Clase C", "Clase B", "Clase A"], "respuestas": ["Clase D"], "explicacion": "Clase D: sin alimentadores, alumbrado ≤ 10 kW y fuerza ≤ 5 kW."},
    {"tipo": "alternativas", "pregunta": "Una fábrica en baja tensión con 70 kW de fuerza motriz. ¿Licencia mínima?", "opciones": ["Clase B", "Clase C", "Clase D", "Solo clase A"], "respuestas": ["Clase B"], "explicacion": "70 kW de fuerza supera el límite de 50 kW de la clase C. La B llega a 500 kW en BT."},
    {"tipo": "alternativas", "pregunta": "Una instalación en media tensión. ¿Qué licencia se requiere?", "opciones": ["Clase A", "Clase B", "Clase C", "Cualquiera con experiencia"], "respuestas": ["Clase A"], "explicacion": "Solo la clase A cubre alta tensión (además de baja), sin límite de potencia."},
    {"tipo": "alternativas", "pregunta": "¿Cuál de estos cambios NO es una modificación según el art. 18° del DS 8?", "opciones": ["Cambiar una ampolleta por una LED del mismo portalámparas", "Aumentar la capacidad de la instalación", "Cualquier cambio en una instalación de media tensión", "Variar los circuitos en zonas de seguridad"], "respuestas": ["Cambiar una ampolleta por una LED del mismo portalámparas"], "explicacion": "Cambiar una ampolleta no altera el diseño ni la topología. Las otras tres están en la lista del art. 18°."},
    {"tipo": "alternativas", "pregunta": "¿En qué sistema se declara una instalación a la SEC y quién lo hace?", "opciones": ["En el e-declarador, el instalador autorizado con su clave", "En la oficina de la distribuidora, el propietario", "En el municipio, el arquitecto", "No se declara: solo se avisa por teléfono"], "respuestas": ["En el e-declarador, el instalador autorizado con su clave"], "explicacion": "RIC N°19, 9.1.2 y 9.1.3: el instalador es el responsable de la documentación que ingresa."},
    {"tipo": "numero", "pregunta": "Quieres poner en servicio una instalación un lunes, sin feriados en medio. Con 15 días hábiles de anticipación, ¿cuántos días corridos antes debes declarar, como mínimo?", "respuesta": 21, "tolerancia": 0, "unidad": "días", "explicacion": "15 días hábiles = 3 semanas = 21 días corridos (art. 22°: los plazos son en días hábiles)."},
    {"tipo": "numero", "pregunta": "Empalme monofásico de 220 V con protección de {I} A. ¿Potencia máxima en kVA? (2 decimales)", "params": {"I": [6, 63, 1]}, "formula": "220*I/1000", "tolerancia": 0.01, "unidad": "kVA", "explicacion": "P = V × I = 220 × {I} = {=220*I} VA = {=220*I/1000} kVA."},
    {"tipo": "alternativas", "pregunta": "La fachada de una casa está a {d} m de la puerta de acceso desde la calle. ¿Dónde va el medidor?", "params": {"d": [16, 40, 1]}, "opciones": ["Cerca de la línea de cierre, en una estructura exclusiva", "En la fachada de la casa", "Dentro de la casa", "En el lugar que elija el propietario"], "respuestas": ["Cerca de la línea de cierre, en una estructura exclusiva"], "explicacion": "{d} m es más de 15 m: la fachada queda fuera del semicírculo (RIC N°01, 7.2 y 7.3)."},
    {"tipo": "alternativas", "pregunta": "¿Puede la distribuidora conectar una instalación nueva que no fue comunicada a la SEC?", "opciones": ["No: el art. 18° se lo prohíbe", "Sí, si el cliente paga", "Sí, si la instalación es pequeña", "Sí, por 30 días provisorios"], "respuestas": ["No: el art. 18° se lo prohíbe"], "explicacion": "Las distribuidoras no pueden conectar instalaciones que no fueron previamente comunicadas por un instalador autorizado, con su verificación de tercera parte (art. 18°)."},
    {"tipo": "escritura", "pregunta": "En 70+ palabras: explica a un cliente qué trámites hay para tener luz en una casa nueva y quién responde por la instalación antes y después de energizarla.", "minPalabras": 70, "obligatorias": ["SEC", "factibilidad", "propietario", "instalador"]}
  ],
  "repaso": [
    {"tipo": "alternativas", "etiqueta": "Contacto indirecto", "pregunta": "Una carcasa metálica quedó energizada por una falla de aislación. ¿Qué protege a quien la toca?", "opciones": ["El diferencial y la puesta a tierra", "El termomagnético", "Un conductor más grueso", "El medidor"], "respuestas": ["El diferencial y la puesta a tierra"], "explicacion": "Contacto indirecto: la tierra da camino a la falla y el diferencial corta."},
    {"tipo": "alternativas", "etiqueta": "Sobrecarga", "pregunta": "Varios artefactos en un mismo circuito calientan el cable sin que haya falla. Es…", "opciones": ["una sobrecarga: actúa la parte térmica del termomagnético", "un cortocircuito: actúa el diferencial", "un contacto directo", "normal"], "respuestas": ["una sobrecarga: actúa la parte térmica del termomagnético"], "explicacion": "Exceso de corriente sostenido: la protección térmica lo detecta."},
    {"tipo": "alternativas", "etiqueta": "Quién dicta y fiscaliza", "pregunta": "Los pliegos RIC los dicta… y fiscaliza…", "opciones": ["la SEC / la SEC", "el Ministerio / la distribuidora", "la distribuidora / la SEC", "el municipio / la SEC"], "respuestas": ["la SEC / la SEC"], "explicacion": "DS 8, arts. 12° y 20°."},
    {"tipo": "alternativas", "etiqueta": "Licencia por potencia", "pregunta": "Alumbrado {a} kW, fuerza {f} kW, alimentadores de 7 kW por fase y 50 m. ¿Licencia mínima?", "params": {"a": [12, 95, 1], "f": [6, 48, 1]}, "opciones": ["Clase C", "Clase D", "Clase B", "Clase A"], "respuestas": ["Clase C"], "explicacion": "Alumbrado ≤ 100, fuerza ≤ 50 y alimentadores ≤ 10 kW/fase y 100 m: clase C. La D no admite alimentadores."},
    {"tipo": "alternativas", "etiqueta": "Licencia con riesgo de explosión", "pregunta": "Un recinto con riesgo de explosión de 80 kW en BT necesita como mínimo…", "opciones": ["clase B", "clase C", "clase D", "no necesita licencia"], "respuestas": ["clase B"], "explicacion": "La B incluye expresamente el riesgo de explosión o incendio."},
    {"tipo": "alternativas", "etiqueta": "Modificaciones", "pregunta": "Agregar cargas que aumentan la capacidad de una casa…", "opciones": ["es una modificación y se declara", "no requiere nada si es casa particular", "solo requiere avisar a la distribuidora", "solo requiere boleta"], "respuestas": ["es una modificación y se declara"], "explicacion": "DS 8, arts. 16° y 18° a)."},
    {"tipo": "numero", "etiqueta": "Días hábiles", "pregunta": "¿Cuántos días corridos son 15 días hábiles contando hacia atrás desde un lunes, sin feriados?", "respuesta": 21, "tolerancia": 0, "unidad": "días", "explicacion": "3 semanas de lunes a viernes = 21 días corridos."},
    {"tipo": "alternativas", "etiqueta": "Medidor a 15 m", "pregunta": "La fachada está a {d} m de la puerta de acceso. El medidor va…", "params": {"d": [5, 14, 1]}, "opciones": ["en la fachada principal, visible desde la calle", "en un poste en la reja, obligatoriamente", "dentro de la casa", "donde decida el cliente"], "respuestas": ["en la fachada principal, visible desde la calle"], "explicacion": "{d} m ≤ 15 m: dentro del semicírculo del RIC N°01, 7.2."},
    {"tipo": "alternativas", "etiqueta": "Declaración devuelta", "pregunta": "Si la SEC devuelve tu declaración con observaciones…", "opciones": ["corriges y sigues con la misma declaración", "ingresas una nueva", "ingresas dos en paralelo", "pides conexión igual"], "respuestas": ["corriges y sigues con la misma declaración"], "explicacion": "RIC N°19, 9.2.10."},
    {"tipo": "numero", "etiqueta": "Potencia monofásica", "pregunta": "Empalme de 220 V y {I} A. ¿kVA máximos? (2 decimales)", "params": {"I": [10, 63, 1]}, "formula": "220*I/1000", "tolerancia": 0.01, "unidad": "kVA", "explicacion": "220 × {I} / 1.000 = {=220*I/1000} kVA."}
  ],
  "ficha": {
    "ideas": ["La norma va desde el **punto de conexión** hacia adentro y cubre todo el ciclo: diseño, construcción, puesta en servicio, operación, reparación y mantención.", "Objetivo único: **seguridad de personas y cosas**. Dos peligros: **incendio** y **choque eléctrico**.", "**Termomagnético** protege al conductor; **diferencial + puesta a tierra** protegen a la persona.", "Pirámide: Ley → **DS 8** (qué y quién) → **19 pliegos RIC** de la SEC (cómo) → IEC citadas. Licencias: **DS 92**.", "Trámite: factibilidad → proyecto → ejecución → verificación → **e-declarador** (15 días hábiles antes) → inscripción SEC → conexión → mantención."],
    "formulas": ["Potencia monofásica: P (VA) = V × I", "Potencia trifásica: P (VA) = √3 × V × I", "15 días hábiles ≈ 21 días corridos (sin feriados)"],
    "normas": ["**DS 8 art. 1°**: alcance y objetivo (seguridad).", "**Art. 4° c**: definición de instalación de consumo.", "**Arts. 5°, 6°, 10°**: propietario responde por mantener; quien diseña/construye/modifica responde por cumplir; multas y/o desconexión.", "**Arts. 7° y 8°**: proyecto técnicamente elaborado; instalador autorizado de la clase que corresponda (DS 92).", "**Art. 13°**: el propietario guarda las declaraciones y el plano definitivo.", "**Art. 15°**: factibilidad técnica de suministro.", "**Arts. 16°, 17°, 18°**: se declaran instalaciones nuevas, modificaciones y provisorias; comunicación previa; qué es modificación; la distribuidora no conecta sin comunicación.", "**Art. 22°**: plazos en días hábiles.", "**RIC N°19, 9.1–9.2**: e-declarador, antecedentes, declaración devuelta.", "**RIC N°01, 7.2–7.3**: medidor en fachada dentro de 15 m; si no, cerca de la línea de cierre.", "**DS 92**: A sin límite · B ≤ 500 kW (explosivos, espectáculos) · C alumbrado ≤ 100 kW, fuerza ≤ 50 kW, alimentadores ≤ 10 kW/fase y 100 m · D alumbrado ≤ 10 kW, fuerza ≤ 5 kW, sin alimentadores."]
  },
  "accion": "Sal a mirar el medidor de tu casa (o de tu negocio): ¿está en la fachada, visible desde la calle y a menos de 15 m de la puerta? Mira la placa del medidor y el automático del empalme: anota la tensión (220 V o 380 V) y la corriente (A), y calcula la potencia con P = V × I. Si tienes una cuenta de luz, busca ahí la potencia conectada y compárala.",
  "calculadoras": ["potencia_electrica"],
  "terminos": [
    {"es": "instalación de consumo", "en": "electrical installation (consumer)", "definicion": "Aparatos, equipos, canalizaciones y circuitos que usan la energía eléctrica, hasta el punto de conexión con la red (DS 8 art. 4° c).", "ejemplo": "The consumer installation starts at the connection point."},
    {"es": "punto de conexión", "en": "point of connection", "definicion": "Límite entre la red de la distribuidora y la instalación del cliente.", "ejemplo": "The distributor is responsible up to the point of connection."},
    {"es": "contacto directo", "en": "direct contact", "definicion": "Tocar una parte activa (normalmente energizada).", "ejemplo": "Enclosures protect against direct contact."},
    {"es": "contacto indirecto", "en": "indirect contact (fault protection)", "definicion": "Tocar una masa que quedó energizada por una falla de aislación.", "ejemplo": "Earthing and RCDs protect against indirect contact."},
    {"es": "sobrecarga", "en": "overload", "definicion": "Corriente mayor a la admisible del circuito, sin falla.", "ejemplo": "An overload heats the cable."},
    {"es": "cortocircuito", "en": "short circuit", "definicion": "Falla de impedancia casi nula entre conductores, con corriente muy alta.", "ejemplo": "The breaker trips on a short circuit."},
    {"es": "factibilidad técnica de suministro", "en": "supply feasibility", "definicion": "Condiciones técnicas y económicas que entrega la distribuidora para conectar o modificar una instalación (DS 8 art. 4° a).", "ejemplo": "Request supply feasibility before designing."},
    {"es": "verificación de tercera parte", "en": "third-party verification", "definicion": "Revisión del cumplimiento hecha por un tercero autorizado por la SEC (DS 8 art. 4° g).", "ejemplo": "Third-party verification is attached to the declaration."},
    {"es": "planos as-built", "en": "as-built drawings", "definicion": "Planos de cómo quedó construida realmente la instalación.", "ejemplo": "Submit as-built drawings with the declaration."}
  ],
  "fuentes": [
    {"titulo": "Decreto 8 (2019), Ministerio de Energía — texto en BCN (Ley Chile)", "url": "https://bcn.cl/2etj7"},
    {"titulo": "SEC — Reglamento de seguridad DS 8 y pliegos técnicos RIC", "url": "https://www.sec.cl/reglamento-de-seguridad-de-las-instalaciones-de-consumo-de-energia-electrica-decreto-08/"},
    {"titulo": "SEC — Entrada en vigencia de los pliegos (12-07-2021)", "url": "https://sec.custhelp.com/app/answers/detail/a_id/1273/~/consulta-por-entrada-en-vigencia-de-los-nuevos-pliegos-t%C3%A9cnicos-ric,-decreto"},
    {"titulo": "SEC — Alcance de las licencias de instalador eléctrico", "url": "https://sec.custhelp.com/app/answers/detail/a_id/584/~/alcance-de-licencias-de-instalador-el%C3%A9ctrico"},
    {"titulo": "SEC — ¿Qué instalaciones puede declarar cada clase?", "url": "https://sec.custhelp.com/app/answers/detail/a_id/254/~/%C2%BFqu%C3%A9-tipo-de-instalaciones-puede-declarar-cada-clase"},
    {"titulo": "Pliegos RIC N°01 (Empalmes) y N°19 (Puesta en servicio) — PDF oficiales (Drive: Electricidad/Pliegos RIC)", "url": "https://www.sec.cl/reglamento-de-seguridad-de-las-instalaciones-de-consumo-de-energia-electrica-decreto-08/"}
  ]
}
);
